export const PHOTO_TOOL_STYLE_IDS = [
  'print_professional_transparent',
  'print_professional_blue_png',
  'print_professional_red_png',
  'print_child_id_transparent',
  'print_child_id_blue_png',
  'print_child_id_red_png',
  'print_student_id_transparent',
  'print_student_id_blue_png',
  'print_student_id_red_png',
] as const

export type PhotoToolStyleId = (typeof PHOTO_TOOL_STYLE_IDS)[number]

export const PHOTO_TOOL_STYLE_CONFIGS = [
  {
    id: 'print_professional_transparent',
    name: 'Professional ID Photo(White)',
    category: 'photo_tools',
    prompt: 'professional ID photo portrait for printing and PNG export, adult business profile, formal clean grooming, neutral expression, front-facing head and shoulders, centered composition, even studio lighting, realistic natural skin texture, clean pure white background, high resolution',
    negative: 'colored background, blue background, red background, scenic background, office background, gradient, texture, shadow, border, watermark, text, logo, hat, sunglasses, exaggerated smile, distorted face, extra limbs, low quality, blurry',
    sort_order: 570,
    category_order: 5,
    style_order: 10,
    selection_count: 0,
    last_selected_at: null,
    localized_names: {
      en: 'Professional ID Photo(White)',
      es: 'Foto ID profesional(fondo blanco)',
      fr: 'Photo ID professionnelle(fond blanc)',
      de: 'Professionelles ID-Foto(weisser Hintergrund)',
      ja: 'プロ向け証明写真(白)',
    },
    localized_category_labels: {
      en: 'ID Photo And PNG',
      es: 'Foto ID y PNG',
      fr: 'Photo ID et PNG',
      de: 'Passfoto und PNG',
      ja: '証明写真とPNG',
    },
  },
  {
    id: 'print_professional_blue_png',
    name: 'Professional ID Photo(Blue)',
    category: 'photo_tools',
    prompt: 'professional ID photo portrait for printing and PNG export, adult business profile, formal clean grooming, neutral expression, front-facing head and shoulders, centered composition, even studio lighting, realistic natural skin texture, clean solid blue ID photo background, official document photo blue backdrop, high resolution',
    negative: 'white background, red background, scenic background, office background, gradient, texture, shadow, border, watermark, text, logo, hat, sunglasses, exaggerated smile, distorted face, extra limbs, low quality, blurry',
    sort_order: 580,
    category_order: 5,
    style_order: 20,
    selection_count: 0,
    last_selected_at: null,
    localized_names: {
      en: 'Professional ID Photo(Blue)',
      es: 'Foto ID profesional(fondo azul)',
      fr: 'Photo ID professionnelle(fond bleu)',
      de: 'Professionelles ID-Foto(blauer Hintergrund)',
      ja: 'プロ向け証明写真(青)',
    },
    localized_category_labels: {
      en: 'ID Photo And PNG',
      es: 'Foto ID y PNG',
      fr: 'Photo ID et PNG',
      de: 'Passfoto und PNG',
      ja: '証明写真とPNG',
    },
  },
  {
    id: 'print_professional_red_png',
    name: 'Professional ID Photo(Red)',
    category: 'photo_tools',
    prompt: 'professional ID photo portrait for printing and PNG export, adult business profile, formal clean grooming, neutral expression, front-facing head and shoulders, centered composition, even studio lighting, realistic natural skin texture, clean solid red ID photo background, official document photo red backdrop, high resolution',
    negative: 'white background, blue background, scenic background, office background, gradient, texture, shadow, border, watermark, text, logo, hat, sunglasses, exaggerated smile, distorted face, extra limbs, low quality, blurry',
    sort_order: 590,
    category_order: 5,
    style_order: 30,
    selection_count: 0,
    last_selected_at: null,
    localized_names: {
      en: 'Professional ID Photo(Red)',
      es: 'Foto ID profesional(fondo rojo)',
      fr: 'Photo ID professionnelle(fond rouge)',
      de: 'Professionelles ID-Foto(roter Hintergrund)',
      ja: 'プロ向け証明写真(赤)',
    },
    localized_category_labels: {
      en: 'ID Photo And PNG',
      es: 'Foto ID y PNG',
      fr: 'Photo ID et PNG',
      de: 'Passfoto und PNG',
      ja: '証明写真とPNG',
    },
  },
  {
    id: 'print_child_id_transparent',
    name: 'Child ID Photo(White)',
    category: 'photo_tools',
    prompt: 'child ID photo portrait for printing and PNG export, natural child face, age-appropriate neat clothing, neutral gentle expression, front-facing head and shoulders, centered composition, even soft studio lighting, realistic natural skin texture, clean pure white background, high resolution',
    negative: 'adult appearance, colored background, blue background, red background, toy background, cartoon style, exaggerated smile, crying, hat, sunglasses, shadow, border, watermark, text, distorted face, extra limbs, low quality, blurry',
    sort_order: 600,
    category_order: 5,
    style_order: 40,
    selection_count: 0,
    last_selected_at: null,
    localized_names: {
      en: 'Child ID Photo(White)',
      es: 'Foto ID infantil(fondo blanco)',
      fr: 'Photo ID enfant(fond blanc)',
      de: 'Kinder-ID-Foto(weisser Hintergrund)',
      ja: '子ども証明写真(白)',
    },
    localized_category_labels: {
      en: 'ID Photo And PNG',
      es: 'Foto ID y PNG',
      fr: 'Photo ID et PNG',
      de: 'Passfoto und PNG',
      ja: '証明写真とPNG',
    },
  },
  {
    id: 'print_child_id_blue_png',
    name: 'Child ID Photo(Blue)',
    category: 'photo_tools',
    prompt: 'child ID photo portrait for printing and PNG export, natural child face, age-appropriate neat clothing, neutral gentle expression, front-facing head and shoulders, centered composition, even soft studio lighting, realistic natural skin texture, clean solid blue ID photo background, official document photo blue backdrop, high resolution',
    negative: 'adult appearance, white background, red background, toy background, cartoon style, exaggerated smile, crying, hat, sunglasses, shadow, border, watermark, text, distorted face, extra limbs, low quality, blurry',
    sort_order: 610,
    category_order: 5,
    style_order: 50,
    selection_count: 0,
    last_selected_at: null,
    localized_names: {
      en: 'Child ID Photo(Blue)',
      es: 'Foto ID infantil(fondo azul)',
      fr: 'Photo ID enfant(fond bleu)',
      de: 'Kinder-ID-Foto(blauer Hintergrund)',
      ja: '子ども証明写真(青)',
    },
    localized_category_labels: {
      en: 'ID Photo And PNG',
      es: 'Foto ID y PNG',
      fr: 'Photo ID et PNG',
      de: 'Passfoto und PNG',
      ja: '証明写真とPNG',
    },
  },
  {
    id: 'print_child_id_red_png',
    name: 'Child ID Photo(Red)',
    category: 'photo_tools',
    prompt: 'child ID photo portrait for printing and PNG export, natural child face, age-appropriate neat clothing, neutral gentle expression, front-facing head and shoulders, centered composition, even soft studio lighting, realistic natural skin texture, clean solid red ID photo background, official document photo red backdrop, high resolution',
    negative: 'adult appearance, white background, blue background, toy background, cartoon style, exaggerated smile, crying, hat, sunglasses, shadow, border, watermark, text, distorted face, extra limbs, low quality, blurry',
    sort_order: 620,
    category_order: 5,
    style_order: 60,
    selection_count: 0,
    last_selected_at: null,
    localized_names: {
      en: 'Child ID Photo(Red)',
      es: 'Foto ID infantil(fondo rojo)',
      fr: 'Photo ID enfant(fond rouge)',
      de: 'Kinder-ID-Foto(roter Hintergrund)',
      ja: '子ども証明写真(赤)',
    },
    localized_category_labels: {
      en: 'ID Photo And PNG',
      es: 'Foto ID y PNG',
      fr: 'Photo ID et PNG',
      de: 'Passfoto und PNG',
      ja: '証明写真とPNG',
    },
  },
  {
    id: 'print_student_id_transparent',
    name: 'Student ID Photo(White)',
    category: 'photo_tools',
    prompt: 'student ID photo portrait for printing and PNG export, school application photo, neat student clothing, clean youthful appearance, neutral friendly expression, front-facing head and shoulders, centered composition, even studio lighting, realistic natural skin texture, clean pure white background, high resolution',
    negative: 'colored background, blue background, red background, classroom background, campus background, dramatic pose, hat, sunglasses, heavy makeup, shadow, border, watermark, text, distorted face, extra limbs, low quality, blurry',
    sort_order: 630,
    category_order: 5,
    style_order: 70,
    selection_count: 0,
    last_selected_at: null,
    localized_names: {
      en: 'Student ID Photo(White)',
      es: 'Foto ID estudiante(fondo blanco)',
      fr: 'Photo ID etudiant(fond blanc)',
      de: 'Studenten-ID-Foto(weisser Hintergrund)',
      ja: '学生証明写真(白)',
    },
    localized_category_labels: {
      en: 'ID Photo And PNG',
      es: 'Foto ID y PNG',
      fr: 'Photo ID et PNG',
      de: 'Passfoto und PNG',
      ja: '証明写真とPNG',
    },
  },
  {
    id: 'print_student_id_blue_png',
    name: 'Student ID Photo(Blue)',
    category: 'photo_tools',
    prompt: 'student ID photo portrait for printing and PNG export, school application photo, neat student clothing, clean youthful appearance, neutral friendly expression, front-facing head and shoulders, centered composition, even studio lighting, realistic natural skin texture, clean solid blue ID photo background, official document photo blue backdrop, high resolution',
    negative: 'white background, red background, classroom background, campus background, dramatic pose, hat, sunglasses, heavy makeup, shadow, border, watermark, text, distorted face, extra limbs, low quality, blurry',
    sort_order: 640,
    category_order: 5,
    style_order: 80,
    selection_count: 0,
    last_selected_at: null,
    localized_names: {
      en: 'Student ID Photo(Blue)',
      es: 'Foto ID estudiante(fondo azul)',
      fr: 'Photo ID etudiant(fond bleu)',
      de: 'Studenten-ID-Foto(blauer Hintergrund)',
      ja: '学生証明写真(青)',
    },
    localized_category_labels: {
      en: 'ID Photo And PNG',
      es: 'Foto ID y PNG',
      fr: 'Photo ID et PNG',
      de: 'Passfoto und PNG',
      ja: '証明写真とPNG',
    },
  },
  {
    id: 'print_student_id_red_png',
    name: 'Student ID Photo(Red)',
    category: 'photo_tools',
    prompt: 'student ID photo portrait for printing and PNG export, school application photo, neat student clothing, clean youthful appearance, neutral friendly expression, front-facing head and shoulders, centered composition, even studio lighting, realistic natural skin texture, clean solid red ID photo background, official document photo red backdrop, high resolution',
    negative: 'white background, blue background, classroom background, campus background, dramatic pose, hat, sunglasses, heavy makeup, shadow, border, watermark, text, distorted face, extra limbs, low quality, blurry',
    sort_order: 650,
    category_order: 5,
    style_order: 90,
    selection_count: 0,
    last_selected_at: null,
    localized_names: {
      en: 'Student ID Photo(Red)',
      es: 'Foto ID estudiante(fondo rojo)',
      fr: 'Photo ID etudiant(fond rouge)',
      de: 'Studenten-ID-Foto(roter Hintergrund)',
      ja: '学生証明写真(赤)',
    },
    localized_category_labels: {
      en: 'ID Photo And PNG',
      es: 'Foto ID y PNG',
      fr: 'Photo ID et PNG',
      de: 'Passfoto und PNG',
      ja: '証明写真とPNG',
    },
  },
] as const

export function isPhotoToolStyleId(styleId: string): styleId is PhotoToolStyleId {
  return (PHOTO_TOOL_STYLE_IDS as readonly string[]).includes(styleId)
}
