export const PHOTO_TOOL_STYLE_IDS = [
  'print_professional_transparent',
  'print_professional_blue_png',
  'print_professional_red_png',
  'print_student_id_transparent',
  'print_student_id_transparent_male',
  'print_student_id_blue_png',
  'print_student_id_red_png',
  'print_men_suit',
  'print_men_shirt',
  'print_women_suit',
  'print_women_shirt',
  'print_child_boy',
  'print_child_girl',
] as const

export type PhotoToolStyleId = (typeof PHOTO_TOOL_STYLE_IDS)[number]

export const PHOTO_TOOL_STYLE_CONFIGS = [
  {
    id: 'print_professional_transparent',
    name: 'Professional ID Photo(White)',
    category: 'photo_tools',
    prompt: 'professional ID photo portrait for printing and PNG export, adult business profile, formal clean grooming, neutral expression, front-facing head and shoulders, centered composition, even studio lighting, realistic natural skin texture, clean pure white background, high resolution',
    negative: 'colored background, blue background, red background, scenic background, office background, gradient, texture, shadow, border, watermark, text, logo, hat, sunglasses, exaggerated smile, distorted face, extra limbs, low quality, blurry',
    sort_order: 570,
    category_order: 5,
    style_order: 10,
    selection_count: 0,
    last_selected_at: null,
    localized_names: {
      en: 'Professional ID Photo(White)',
      es: 'Foto ID profesional(fondo blanco)',
      fr: 'Photo ID professionnelle(fond blanc)',
      de: 'Professionelles ID-Foto(weisser Hintergrund)',
      ja: 'プロ向け証明写真(白)',
    },
    localized_category_labels: {
      en: 'ID Photo And PNG',
      es: 'Foto ID y PNG',
      fr: 'Photo ID et PNG',
      de: 'Passfoto und PNG',
      ja: '証明写真とPNG',
    },
  },
  {
    id: 'print_professional_blue_png',
    name: 'Professional ID Photo(Blue)',
    category: 'photo_tools',
    prompt: 'professional ID photo portrait for printing and PNG export, adult business profile, formal clean grooming, neutral expression, front-facing head and shoulders, centered composition, even studio lighting, realistic natural skin texture, clean solid blue #428eda ID photo background, official document photo blue backdrop, high resolution',
    negative: 'white background, red background, scenic background, office background, gradient, texture, shadow, border, watermark, text, logo, hat, sunglasses, exaggerated smile, distorted face, extra limbs, low quality, blurry',
    sort_order: 580,
    category_order: 5,
    style_order: 20,
    selection_count: 0,
    last_selected_at: null,
    localized_names: {
      en: 'Professional ID Photo(Blue)',
      es: 'Foto ID profesional(fondo azul)',
      fr: 'Photo ID professionnelle(fond bleu)',
      de: 'Professionelles ID-Foto(blauer Hintergrund)',
      ja: 'プロ向け証明写真(青)',
    },
    localized_category_labels: {
      en: 'ID Photo And PNG',
      es: 'Foto ID y PNG',
      fr: 'Photo ID et PNG',
      de: 'Passfoto und PNG',
      ja: '証明写真とPNG',
    },
  },
  {
    id: 'print_professional_red_png',
    name: 'Professional ID Photo(Red)',
    category: 'photo_tools',
    prompt: 'professional ID photo portrait for printing and PNG export, adult business profile, formal clean grooming, neutral expression, front-facing head and shoulders, centered composition, even studio lighting, realistic natural skin texture, clean solid red #d62829 ID photo background, official document photo red backdrop, high resolution',
    negative: 'white background, blue background, scenic background, office background, gradient, texture, shadow, border, watermark, text, logo, hat, sunglasses, exaggerated smile, distorted face, extra limbs, low quality, blurry',
    sort_order: 590,
    category_order: 5,
    style_order: 30,
    selection_count: 0,
    last_selected_at: null,
    localized_names: {
      en: 'Professional ID Photo(Red)',
      es: 'Foto ID profesional(fondo rojo)',
      fr: 'Photo ID professionnelle(fond rouge)',
      de: 'Professionelles ID-Foto(roter Hintergrund)',
      ja: 'プロ向け証明写真(赤)',
    },
    localized_category_labels: {
      en: 'ID Photo And PNG',
      es: 'Foto ID y PNG',
      fr: 'Photo ID et PNG',
      de: 'Passfoto und PNG',
      ja: '証明写真とPNG',
    },
  },
  {
    id: 'print_student_id_transparent',
    name: 'Student ID Photo(White Female)',
    category: 'student_kids',
    prompt: 'student ID photo portrait for printing and PNG export, school application photo, young female student, neat student clothing, clean youthful appearance, neutral friendly expression, front-facing head and shoulders, centered composition, even studio lighting, realistic natural skin texture, clean pure white background, high resolution',
    negative: 'colored background, blue background, red background, classroom background, campus background, dramatic pose, hat, sunglasses, heavy makeup, shadow, border, watermark, text, distorted face, extra limbs, low quality, blurry',
    sort_order: 630,
    category_order: 7,
    style_order: 10,
    selection_count: 0,
    last_selected_at: null,
    localized_names: {
      en: 'Student ID Photo(White Female)',
      es: 'Foto ID estudiante(fondo blanco femenino)',
      fr: 'Photo ID etudiant(fond blanc femme)',
      de: 'Studenten-ID-Foto(weisser Hintergrund Damen)',
      ja: '学生証明写真(白・女性)',
    },
    localized_category_labels: {
      en: 'Student & Kids',
      es: 'Estudiante y Ninos',
      fr: 'Etudiant et Enfants',
      de: 'Studenten und Kinder',
      ja: '学生・子供',
    },
  },
  {
    id: 'print_student_id_transparent_male',
    name: 'Student ID Photo(White Male)',
    category: 'student_kids',
    prompt: 'student ID photo portrait for printing and PNG export, school application photo, young male student, neat student clothing, clean youthful appearance, neutral friendly expression, front-facing head and shoulders, centered composition, even studio lighting, realistic natural skin texture, clean pure white background, high resolution',
    negative: 'colored background, blue background, red background, classroom background, campus background, dramatic pose, hat, sunglasses, heavy makeup, shadow, border, watermark, text, distorted face, extra limbs, low quality, blurry',
    sort_order: 625,
    category_order: 7,
    style_order: 5,
    selection_count: 0,
    last_selected_at: null,
    localized_names: {
      en: 'Student ID Photo(White Male)',
      es: 'Foto ID estudiante(fondo blanco masculino)',
      fr: 'Photo ID etudiant(fond blanc homme)',
      de: 'Studenten-ID-Foto(weisser Hintergrund Herren)',
      ja: '学生証明写真(白・男性)',
    },
    localized_category_labels: {
      en: 'Student & Kids',
      es: 'Estudiante y Ninos',
      fr: 'Etudiant et Enfants',
      de: 'Studenten und Kinder',
      ja: '学生・子供',
    },
  },
  {
    id: 'print_student_id_blue_png',
    name: 'Student ID Photo(Blue)',
    category: 'student_kids',
    prompt: 'student ID photo portrait for printing and PNG export, school application photo, neat student clothing, clean youthful appearance, neutral friendly expression, front-facing head and shoulders, centered composition, even studio lighting, realistic natural skin texture, clean solid blue #428eda ID photo background, official document photo blue backdrop, high resolution',
    negative: 'white background, red background, classroom background, campus background, dramatic pose, hat, sunglasses, heavy makeup, shadow, border, watermark, text, distorted face, extra limbs, low quality, blurry',
    sort_order: 640,
    category_order: 3,
    style_order: 20,
    selection_count: 0,
    last_selected_at: null,
    localized_names: {
      en: 'Student ID Photo(Blue)',
      es: 'Foto ID estudiante(fondo azul)',
      fr: 'Photo ID etudiant(fond bleu)',
      de: 'Studenten-ID-Foto(blauer Hintergrund)',
      ja: '学生証明写真(青)',
    },
    localized_category_labels: {
      en: 'Student & Kids',
      es: 'Estudiante y Ninos',
      fr: 'Etudiant et Enfants',
      de: 'Studenten und Kinder',
      ja: '学生・子供',
    },
  },
  {
    id: 'print_student_id_red_png',
    name: 'Student ID Photo(Red)',
    category: 'student_kids',
    prompt: 'student ID photo portrait for printing and PNG export, school application photo, neat student clothing, clean youthful appearance, neutral friendly expression, front-facing head and shoulders, centered composition, even studio lighting, realistic natural skin texture, clean solid red #d62829 ID photo background, official document photo red backdrop, high resolution',
    negative: 'white background, blue background, classroom background, campus background, dramatic pose, hat, sunglasses, heavy makeup, shadow, border, watermark, text, distorted face, extra limbs, low quality, blurry',
    sort_order: 650,
    category_order: 3,
    style_order: 30,
    selection_count: 0,
    last_selected_at: null,
    localized_names: {
      en: 'Student ID Photo(Red)',
      es: 'Foto ID estudiante(fondo rojo)',
      fr: 'Photo ID etudiant(fond rouge)',
      de: 'Studenten-ID-Foto(roter Hintergrund)',
      ja: '学生証明写真(赤)',
    },
    localized_category_labels: {
      en: 'Student & Kids',
      es: 'Estudiante y Ninos',
      fr: 'Etudiant et Enfants',
      de: 'Studenten und Kinder',
      ja: '学生・子供',
    },
  },
  {
    id: 'print_men_suit',
    name: 'Men Suit ID Photo(White)',
    category: 'photo_tools',
    prompt: 'men ID photo portrait for printing and PNG export, adult male in formal dark business suit with tie, formal clean grooming, neutral expression, front-facing head and shoulders, centered composition, even studio lighting, realistic natural skin texture, clean pure white background, high resolution',
    negative: 'female appearance, casual clothes, t-shirt, uniform, colored background, blue background, red background, scenic background, office background, gradient, texture, shadow, border, watermark, text, logo, hat, sunglasses, exaggerated smile, distorted face, extra limbs, low quality, blurry',
    sort_order: 660,
    category_order: 5,
    style_order: 100,
    selection_count: 0,
    last_selected_at: null,
    localized_names: {
      en: 'Men Suit ID Photo(White)',
      es: 'Foto ID hombre con traje(fondo blanco)',
      fr: 'Photo ID homme en costume(fond blanc)',
      de: 'Herren-ID-Foto im Anzug(weisser Hintergrund)',
      ja: '男性スーツ証明写真(白)',
    },
    localized_category_labels: {
      en: 'ID Photo And PNG',
      es: 'Foto ID y PNG',
      fr: 'Photo ID et PNG',
      de: 'Passfoto und PNG',
      ja: '証明写真とPNG',
    },
  },
  {
    id: 'print_men_shirt',
    name: 'Men Shirt ID Photo(White)',
    category: 'photo_tools',
    prompt: 'men ID photo portrait for printing and PNG export, adult male in a crisp formal dress shirt, no tie, formal clean grooming, neutral expression, front-facing head and shoulders, centered composition, even studio lighting, realistic natural skin texture, clean pure white background, high resolution',
    negative: 'female appearance, casual clothes, suit jacket, t-shirt, colored background, blue background, red background, scenic background, office background, gradient, texture, shadow, border, watermark, text, logo, hat, sunglasses, exaggerated smile, distorted face, extra limbs, low quality, blurry',
    sort_order: 670,
    category_order: 5,
    style_order: 110,
    selection_count: 0,
    last_selected_at: null,
    localized_names: {
      en: 'Men Shirt ID Photo(White)',
      es: 'Foto ID hombre con camisa(fondo blanco)',
      fr: 'Photo ID homme en chemise(fond blanc)',
      de: 'Herren-ID-Foto im Hemd(weisser Hintergrund)',
      ja: '男性シャツ証明写真(白)',
    },
    localized_category_labels: {
      en: 'ID Photo And PNG',
      es: 'Foto ID y PNG',
      fr: 'Photo ID et PNG',
      de: 'Passfoto und PNG',
      ja: '証明写真とPNG',
    },
  },
  {
    id: 'print_women_suit',
    name: 'Women Suit ID Photo(White)',
    category: 'photo_tools',
    prompt: 'women ID photo portrait for printing and PNG export, adult female in a formal tailored business suit, formal clean grooming, neutral expression, front-facing head and shoulders, centered composition, even studio lighting, realistic natural skin texture, clean pure white background, high resolution',
    negative: 'male appearance, casual clothes, t-shirt, uniform, colored background, blue background, red background, scenic background, office background, gradient, texture, shadow, border, watermark, text, logo, hat, sunglasses, exaggerated smile, distorted face, extra limbs, low quality, blurry',
    sort_order: 680,
    category_order: 5,
    style_order: 120,
    selection_count: 0,
    last_selected_at: null,
    localized_names: {
      en: 'Women Suit ID Photo(White)',
      es: 'Foto ID mujer con traje(fondo blanco)',
      fr: 'Photo ID femme en tailleur(fond blanc)',
      de: 'Damen-ID-Foto im Kostum(weisser Hintergrund)',
      ja: '女性スーツ証明写真(白)',
    },
    localized_category_labels: {
      en: 'ID Photo And PNG',
      es: 'Foto ID y PNG',
      fr: 'Photo ID et PNG',
      de: 'Passfoto und PNG',
      ja: '証明写真とPNG',
    },
  },
  {
    id: 'print_women_shirt',
    name: 'Women Shirt ID Photo(White)',
    category: 'photo_tools',
    prompt: 'women ID photo portrait for printing and PNG export, adult female in a crisp formal blouse, formal clean grooming, neutral expression, front-facing head and shoulders, centered composition, even studio lighting, realistic natural skin texture, clean pure white background, high resolution',
    negative: 'male appearance, casual clothes, suit jacket, t-shirt, colored background, blue background, red background, scenic background, office background, gradient, texture, shadow, border, watermark, text, logo, hat, sunglasses, exaggerated smile, distorted face, extra limbs, low quality, blurry',
    sort_order: 690,
    category_order: 5,
    style_order: 130,
    selection_count: 0,
    last_selected_at: null,
    localized_names: {
      en: 'Women Shirt ID Photo(White)',
      es: 'Foto ID mujer con camisa(fondo blanco)',
      fr: 'Photo ID femme en chemisier(fond blanc)',
      de: 'Damen-ID-Foto im Blusenhemd(weisser Hintergrund)',
      ja: '女性シャツ証明写真(白)',
    },
    localized_category_labels: {
      en: 'ID Photo And PNG',
      es: 'Foto ID y PNG',
      fr: 'Photo ID et PNG',
      de: 'Passfoto und PNG',
      ja: '証明写真とPNG',
    },
  },
  {
    id: 'print_child_boy',
    name: 'Boy ID Photo(White)',
    category: 'student_kids',
    prompt: 'child ID photo portrait for printing and PNG export, young boy, neat age-appropriate clean clothing, natural gentle expression, front-facing head and shoulders, centered composition, even soft studio lighting, realistic natural skin texture, clean pure white background, high resolution',
    negative: 'adult appearance, girl appearance, casual messy clothes, uniform, colored background, blue background, red background, scenic background, classroom background, cartoon style, crying, hat, sunglasses, shadow, border, watermark, text, distorted face, extra limbs, low quality, blurry',
    sort_order: 700,
    category_order: 3,
    style_order: 40,
    selection_count: 0,
    last_selected_at: null,
    localized_names: {
      en: 'Boy ID Photo(White)',
      es: 'Foto ID nino(fondo blanco)',
      fr: 'Photo ID garcon(fond blanc)',
      de: 'Jungen-ID-Foto(weisser Hintergrund)',
      ja: '男の子証明写真(白)',
    },
    localized_category_labels: {
      en: 'Student & Kids',
      es: 'Estudiante y Ninos',
      fr: 'Etudiant et Enfants',
      de: 'Studenten und Kinder',
      ja: '学生・子供',
    },
  },
  {
    id: 'print_child_girl',
    name: 'Girl ID Photo(White)',
    category: 'student_kids',
    prompt: 'child ID photo portrait for printing and PNG export, young girl, neat age-appropriate clean clothing, natural gentle expression, front-facing head and shoulders, centered composition, even soft studio lighting, realistic natural skin texture, clean pure white background, high resolution',
    negative: 'adult appearance, boy appearance, casual messy clothes, uniform, colored background, blue background, red background, scenic background, classroom background, cartoon style, crying, hat, sunglasses, shadow, border, watermark, text, distorted face, extra limbs, low quality, blurry',
    sort_order: 710,
    category_order: 3,
    style_order: 50,
    selection_count: 0,
    last_selected_at: null,
    localized_names: {
      en: 'Girl ID Photo(White)',
      es: 'Foto ID nina(fondo blanco)',
      fr: 'Photo ID fille(fond blanc)',
      de: 'Madchen-ID-Foto(weisser Hintergrund)',
      ja: '女の子証明写真(白)',
    },
    localized_category_labels: {
      en: 'Student & Kids',
      es: 'Estudiante y Ninos',
      fr: 'Etudiant et Enfants',
      de: 'Studenten und Kinder',
      ja: '学生・子供',
    },
  },
] as const

export function isPhotoToolStyleId(styleId: string): styleId is PhotoToolStyleId {
  return (PHOTO_TOOL_STYLE_IDS as readonly string[]).includes(styleId)
}
