import type { Metadata } from 'next'
import { appConfig } from '@/lib/config'
import { OPEN_GRAPH_LOCALES, languageAlternatesForPath, localePath, type Locale } from '@/lib/i18n'

export const USE_CASE_PAGE_SLUGS = [
  'ai-headshot-linkedin',
  'ai-headshot-corporate',
  'ai-headshot-resume',
  'ai-headshot-studio-style',
  'ai-headshot-professional-photo',
] as const

export type UseCasePageSlug = (typeof USE_CASE_PAGE_SLUGS)[number]

export type UseCasePageContent = {
  title: string
  description: string
  keywords: string[]
  eyebrow: string
  h1: string
  intro: string
  primaryCta: string
  secondaryCta: string
  casesTitle: string
  casesText: string
  cases: { title: string; text: string }[]
  guidanceTitle: string
  guidanceText: string
  checklist: string[]
  linksTitle: string
  linksText: string
  relatedLinks: { href: string; label: string; description: string }[]
  faqTitle: string
  faqText: string
  faqs: { question: string; answer: string }[]
}

export const useCaseHeroImage = '/home-pages/Ai%20headshot-linkedin-professional.jpg'

const englishRelated: Record<UseCasePageSlug, UseCasePageContent['relatedLinks']> = {
  'ai-headshot-linkedin': [
    { href: '/ai-headshot-corporate', label: 'Corporate headshots', description: 'Plan a consistent profile image for teams and company pages.' },
    { href: '/ai-headshot-resume', label: 'Resume photo guidance', description: 'Choose a calmer image for CVs, resumes, and applications.' },
    { href: '/sample', label: 'Sample comparisons', description: 'Compare source selfies with generated professional portraits.' },
    { href: '/questions', label: 'Upload questions', description: 'Check photo quality, credits, and commercial usage before starting.' },
  ],
  'ai-headshot-corporate': [
    { href: '/ai-headshot-linkedin', label: 'LinkedIn profile headshots', description: 'Keep employee LinkedIn photos aligned with the public team page.' },
    { href: '/ai-headshot-studio-style', label: 'Studio-style portraits', description: 'Use a polished background direction when the brand needs formality.' },
    { href: '/sample', label: 'Team-ready samples', description: 'Review examples before setting a style rule for everyone.' },
    { href: '/pricing', label: 'Credit packs', description: 'Pick a one-time pack before generating portraits.' },
  ],
  'ai-headshot-resume': [
    { href: '/ai-headshot-linkedin', label: 'LinkedIn headshots', description: 'Match the application photo with your public profile.' },
    { href: '/ai-headshot-professional-photo', label: 'Professional photo maker', description: 'Build a broader work profile image for bios and directories.' },
    { href: '/questions', label: 'Photo upload FAQ', description: 'Prepare source photos that protect likeness and avoid artifacts.' },
    { href: '/sample', label: 'Resume-style examples', description: 'Inspect realistic examples before choosing a plan.' },
  ],
  'ai-headshot-studio-style': [
    { href: '/ai-headshot-professional-photo', label: 'Professional photo page', description: 'Compare a studio look with a more flexible work profile image.' },
    { href: '/ai-headshot-corporate', label: 'Corporate team headshots', description: 'Apply the same studio direction across staff pages.' },
    { href: '/sample', label: 'Before and after samples', description: 'Use examples to judge background, lighting, and expression.' },
    { href: '/pricing', label: 'View plans', description: 'Choose credits for the number of styles you want to generate.' },
  ],
  'ai-headshot-professional-photo': [
    { href: '/ai-headshot-linkedin', label: 'LinkedIn use case', description: 'Tune the same portrait for recruiter and network discovery.' },
    { href: '/ai-headshot-resume', label: 'Resume use case', description: 'Choose a restrained version for applications and CV contexts.' },
    { href: '/ai-headshot-studio-style', label: 'Studio-style option', description: 'Use a more formal portrait direction when needed.' },
    { href: '/questions', label: 'Common questions', description: 'Understand credits, uploads, downloads, and commercial use.' },
  ],
}

const localizedRelated: Record<Exclude<Locale, 'en'>, Record<UseCasePageSlug, UseCasePageContent['relatedLinks']>> = {
  es: {
    'ai-headshot-linkedin': [
      { href: '/ai-headshot-corporate', label: 'Retratos corporativos', description: 'Mantén una imagen coherente para equipos, webs y perfiles de empresa.' },
      { href: '/ai-headshot-resume', label: 'Foto para CV', description: 'Prepara una versión más sobria cuando el mercado espera foto en el CV.' },
      { href: '/sample', label: 'Ejemplos antes/después', description: 'Compara selfies originales con retratos generados.' },
      { href: '/questions', label: 'Preguntas de subida', description: 'Revisa calidad de fotos, créditos y uso profesional.' },
    ],
    'ai-headshot-corporate': [
      { href: '/ai-headshot-linkedin', label: 'LinkedIn profesional', description: 'Alinea la foto del equipo con su presencia pública.' },
      { href: '/ai-headshot-studio-style', label: 'Estilo estudio', description: 'Usa fondos y luz más formales para marcas conservadoras.' },
      { href: '/sample', label: 'Muestras visuales', description: 'Evalúa parecido, ropa y fondo antes de generar.' },
      { href: '/pricing', label: 'Planes de créditos', description: 'Elige un paquete único para crear los estilos necesarios.' },
    ],
    'ai-headshot-resume': [
      { href: '/ai-headshot-linkedin', label: 'Foto para LinkedIn', description: 'Mantén coherencia entre candidatura y perfil público.' },
      { href: '/ai-headshot-professional-photo', label: 'Foto profesional', description: 'Crea una imagen útil para bio, firma y perfiles.' },
      { href: '/questions', label: 'FAQ de fotos', description: 'Prepara selfies claros y evita resultados con artefactos.' },
      { href: '/sample', label: 'Ejemplos para CV', description: 'Mira muestras realistas antes de elegir plan.' },
    ],
    'ai-headshot-studio-style': [
      { href: '/ai-headshot-professional-photo', label: 'Foto profesional', description: 'Compara un estilo estudio con un perfil más flexible.' },
      { href: '/ai-headshot-corporate', label: 'Equipo corporativo', description: 'Aplica una dirección visual común a todo el equipo.' },
      { href: '/sample', label: 'Antes y después', description: 'Comprueba fondo, iluminación y expresión.' },
      { href: '/pricing', label: 'Ver planes', description: 'Compra créditos según los estilos que quieras generar.' },
    ],
    'ai-headshot-professional-photo': [
      { href: '/ai-headshot-linkedin', label: 'Uso en LinkedIn', description: 'Adapta la imagen para búsqueda, networking y reclutadores.' },
      { href: '/ai-headshot-resume', label: 'Uso en CV', description: 'Prepara una versión sobria para candidaturas.' },
      { href: '/ai-headshot-studio-style', label: 'Estilo estudio', description: 'Elige un look más formal cuando la marca lo requiere.' },
      { href: '/questions', label: 'Preguntas comunes', description: 'Entiende créditos, descargas y uso comercial.' },
    ],
  },
  fr: {
    'ai-headshot-linkedin': [
      { href: '/ai-headshot-corporate', label: 'Portraits corporate', description: 'Gardez une image cohérente entre équipe, site et profils publics.' },
      { href: '/ai-headshot-resume', label: 'Photo de CV', description: 'Préparez une version plus sobre quand la candidature l exige.' },
      { href: '/sample', label: 'Exemples avant/après', description: 'Comparez selfies sources et portraits générés.' },
      { href: '/questions', label: 'Questions d import', description: 'Vérifiez qualité photo, crédits et droits d usage.' },
    ],
    'ai-headshot-corporate': [
      { href: '/ai-headshot-linkedin', label: 'Photo LinkedIn', description: 'Alignez le profil public des collaborateurs avec la page entreprise.' },
      { href: '/ai-headshot-studio-style', label: 'Style studio', description: 'Choisissez une lumière et un fond plus formels pour la marque.' },
      { href: '/sample', label: 'Exemples visuels', description: 'Jugez ressemblance, tenue et arrière-plan avant de générer.' },
      { href: '/pricing', label: 'Packs de crédits', description: 'Achetez un pack unique selon les styles nécessaires.' },
    ],
    'ai-headshot-resume': [
      { href: '/ai-headshot-linkedin', label: 'Portrait LinkedIn', description: 'Gardez une image cohérente entre candidature et profil public.' },
      { href: '/ai-headshot-professional-photo', label: 'Photo professionnelle', description: 'Créez une image utile pour bio, annuaire et signature.' },
      { href: '/questions', label: 'FAQ photos', description: 'Préparez des selfies clairs pour limiter les artefacts.' },
      { href: '/sample', label: 'Exemples CV', description: 'Inspectez des résultats réalistes avant de choisir.' },
    ],
    'ai-headshot-studio-style': [
      { href: '/ai-headshot-professional-photo', label: 'Photo professionnelle', description: 'Comparez un rendu studio avec une photo de profil plus souple.' },
      { href: '/ai-headshot-corporate', label: 'Équipe corporate', description: 'Déployez une direction visuelle commune sur le site équipe.' },
      { href: '/sample', label: 'Avant/après', description: 'Vérifiez fond, lumière et expression.' },
      { href: '/pricing', label: 'Voir les plans', description: 'Choisissez des crédits selon les styles à générer.' },
    ],
    'ai-headshot-professional-photo': [
      { href: '/ai-headshot-linkedin', label: 'Usage LinkedIn', description: 'Adaptez la photo à la découverte recruteur et réseau.' },
      { href: '/ai-headshot-resume', label: 'Usage CV', description: 'Préparez une version sobre pour les candidatures.' },
      { href: '/ai-headshot-studio-style', label: 'Option studio', description: 'Utilisez un rendu plus formel lorsque nécessaire.' },
      { href: '/questions', label: 'Questions courantes', description: 'Comprenez crédits, téléchargements et usage commercial.' },
    ],
  },
  de: {
    'ai-headshot-linkedin': [
      { href: '/ai-headshot-corporate', label: 'Corporate Headshots', description: 'Halte Teamseite, Firmenprofil und öffentliche Profile konsistent.' },
      { href: '/ai-headshot-resume', label: 'Bewerbungsfoto', description: 'Wähle eine ruhigere Version für Lebenslauf und Bewerbung.' },
      { href: '/sample', label: 'Vorher-nachher Beispiele', description: 'Vergleiche Selfies mit generierten Business-Portraits.' },
      { href: '/questions', label: 'Upload Fragen', description: 'Prüfe Fotoqualität, Credits und berufliche Nutzung.' },
    ],
    'ai-headshot-corporate': [
      { href: '/ai-headshot-linkedin', label: 'LinkedIn Profilbild', description: 'Stimme Mitarbeiterprofile mit der öffentlichen Teamseite ab.' },
      { href: '/ai-headshot-studio-style', label: 'Studio-Stil', description: 'Nutze formellere Hintergründe für konservative Marken.' },
      { href: '/sample', label: 'Visuelle Beispiele', description: 'Bewerte Ähnlichkeit, Kleidung und Hintergrund vorab.' },
      { href: '/pricing', label: 'Credit-Pakete', description: 'Kaufe einmalig Credits für die benötigten Stile.' },
    ],
    'ai-headshot-resume': [
      { href: '/ai-headshot-linkedin', label: 'LinkedIn Headshot', description: 'Halte Bewerbung und öffentliches Profil visuell zusammen.' },
      { href: '/ai-headshot-professional-photo', label: 'Professionelles Foto', description: 'Erstelle ein Bild für Bio, Verzeichnis und Signatur.' },
      { href: '/questions', label: 'Foto FAQ', description: 'Bereite klare Selfies vor und vermeide Artefakte.' },
      { href: '/sample', label: 'Bewerbungsfoto Beispiele', description: 'Prüfe realistische Ergebnisse vor der Planauswahl.' },
    ],
    'ai-headshot-studio-style': [
      { href: '/ai-headshot-professional-photo', label: 'Professionelles Foto', description: 'Vergleiche Studio-Look mit einem flexibleren Profilbild.' },
      { href: '/ai-headshot-corporate', label: 'Corporate Team', description: 'Übertrage eine visuelle Richtung auf Teamseiten.' },
      { href: '/sample', label: 'Vorher und nachher', description: 'Prüfe Hintergrund, Licht und Ausdruck.' },
      { href: '/pricing', label: 'Pläne ansehen', description: 'Wähle Credits passend zu den gewünschten Stilen.' },
    ],
    'ai-headshot-professional-photo': [
      { href: '/ai-headshot-linkedin', label: 'LinkedIn Einsatz', description: 'Passe das Bild für Recruiter, Netzwerk und Suche an.' },
      { href: '/ai-headshot-resume', label: 'Lebenslauf Einsatz', description: 'Wähle eine zurückhaltende Version für Bewerbungen.' },
      { href: '/ai-headshot-studio-style', label: 'Studio-Option', description: 'Nutze einen formelleren Look, wenn der Kontext es braucht.' },
      { href: '/questions', label: 'Häufige Fragen', description: 'Verstehe Credits, Downloads und kommerzielle Nutzung.' },
    ],
  },
  ja: {
    'ai-headshot-linkedin': [
      { href: '/ai-headshot-corporate', label: '企業向け写真', description: '社員紹介、会社サイト、公開プロフィールの印象をそろえます。' },
      { href: '/ai-headshot-resume', label: '履歴書向け写真', description: '応募書類で使いやすい落ち着いた写真を準備します。' },
      { href: '/sample', label: '生成サンプル', description: '元写真と生成結果を見比べて品質を確認できます。' },
      { href: '/questions', label: 'よくある質問', description: '写真の選び方、クレジット、商用利用を確認できます。' },
    ],
    'ai-headshot-corporate': [
      { href: '/ai-headshot-linkedin', label: 'LinkedIn用写真', description: '社員の公開プロフィールと会社ページの印象を合わせます。' },
      { href: '/ai-headshot-studio-style', label: 'スタジオ風写真', description: 'よりフォーマルな背景と光の方向性を選べます。' },
      { href: '/sample', label: 'サンプルを見る', description: '顔の自然さ、服装、背景を事前に確認できます。' },
      { href: '/pricing', label: '料金を見る', description: '必要なスタイル数に合わせてクレジットを選べます。' },
    ],
    'ai-headshot-resume': [
      { href: '/ai-headshot-linkedin', label: 'LinkedIn用写真', description: '応募書類と公開プロフィールの見え方をそろえます。' },
      { href: '/ai-headshot-professional-photo', label: '仕事用プロフィール写真', description: '職務経歴、自己紹介、社内プロフィールにも使えます。' },
      { href: '/questions', label: '写真FAQ', description: '明るい元写真を用意して不自然な生成を避けます。' },
      { href: '/sample', label: '履歴書向けサンプル', description: '生成例を見てからプランを選べます。' },
    ],
    'ai-headshot-studio-style': [
      { href: '/ai-headshot-professional-photo', label: '仕事用写真', description: 'スタジオ風と汎用プロフィール写真を比較できます。' },
      { href: '/ai-headshot-corporate', label: '企業チーム向け', description: '社員紹介ページに合う統一感を作れます。' },
      { href: '/sample', label: 'ビフォーアフター', description: '背景、光、表情の違いを確認できます。' },
      { href: '/pricing', label: 'プランを見る', description: '生成したいスタイルに合わせて選べます。' },
    ],
    'ai-headshot-professional-photo': [
      { href: '/ai-headshot-linkedin', label: 'LinkedInで使う', description: '採用担当者や取引先に見られるプロフィール向けです。' },
      { href: '/ai-headshot-resume', label: '履歴書で使う', description: '応募書類向けに落ち着いた写真を選べます。' },
      { href: '/ai-headshot-studio-style', label: 'スタジオ風', description: 'より正式な場面に合う写真を作れます。' },
      { href: '/questions', label: 'よくある質問', description: 'クレジット、ダウンロード、商用利用を確認できます。' },
    ],
  },
}

export const useCasePages: Record<UseCasePageSlug, Record<Locale, UseCasePageContent>> = {
  'ai-headshot-linkedin': {
    en: {
      title: 'AI Headshot for LinkedIn Profiles | Magic-Headshot',
      description: 'Create a realistic AI headshot for LinkedIn profiles, recruiter search, founder bios, and business networking without booking a studio.',
      keywords: ['AI headshot for LinkedIn', 'LinkedIn profile photo maker', 'professional LinkedIn headshot', 'AI LinkedIn photo'],
      eyebrow: 'LinkedIn profile photo use case',
      h1: 'AI Headshot for LinkedIn Profiles That Need a Credible First Impression',
      intro: 'A LinkedIn headshot has to do a different job than a studio portrait. It appears in recruiter search, connection requests, comment threads, sales outreach, speaker bios, and company announcements, often at a very small size. This page is built for professionals who want a clear, approachable image that still feels business-ready. Use it when your current selfie looks too casual, your old corporate photo no longer matches you, or you need a profile refresh before applications, client outreach, or a new role announcement.',
      primaryCta: 'Generate LinkedIn headshots',
      secondaryCta: 'Compare samples',
      casesTitle: 'Where this LinkedIn headshot works best',
      casesText: 'Use the page as a practical brief before generating, especially when one photo needs to support multiple LinkedIn moments.',
      cases: [
        { title: 'Recruiter discovery', text: 'Use a direct, well-lit portrait that stays readable in search results and profile previews.' },
        { title: 'Founder and expert profiles', text: 'Choose a confident but approachable look for investor updates, podcasts, and speaking pages.' },
        { title: 'Sales and client outreach', text: 'Avoid overly stylized images; trust matters more than drama in a cold message preview.' },
      ],
      guidanceTitle: 'LinkedIn-specific guidance',
      guidanceText: 'The strongest LinkedIn image usually feels current, calm, and easy to recognize. Keep the crop close enough for mobile, use simple clothing, and avoid backgrounds that compete with the face.',
      checklist: ['Clear face and eye contact', 'Modern business or smart-casual wardrobe', 'Neutral background with enough contrast', 'Expression that feels reachable, not staged'],
      linksTitle: 'Plan the rest of your profile photo set',
      linksText: 'These pages help you adapt the same generation session for a resume, team page, or comparison review.',
      relatedLinks: englishRelated['ai-headshot-linkedin'],
      faqTitle: 'LinkedIn headshot questions',
      faqText: 'Answers focused on LinkedIn profile use, source photos, and style choices.',
      faqs: [
        { question: 'Can I use the same AI headshot on LinkedIn and a company bio?', answer: 'Yes. Many people use one polished portrait across LinkedIn, company bios, speaker pages, and email signatures, as long as the crop and tone fit each context.' },
        { question: 'What should I upload for a LinkedIn-style result?', answer: 'Upload recent selfies with clear lighting, a visible face, and no heavy filters. A few angles help the generator keep your likeness stable.' },
        { question: 'Should a LinkedIn photo look formal?', answer: 'It should match your field. Corporate, legal, and consulting profiles often benefit from a formal look, while creative or startup roles can use a warmer smart-casual portrait.' },
      ],
    },
    es: {
      title: 'Foto LinkedIn con IA para perfiles profesionales',
      description: 'Crea una foto LinkedIn con IA para reclutadores, networking, ventas y perfiles de empresa sin reservar estudio.',
      keywords: ['foto LinkedIn IA', 'headshot LinkedIn IA', 'foto profesional LinkedIn', 'retrato profesional IA'],
      eyebrow: 'Caso de uso para LinkedIn',
      h1: 'Foto LinkedIn con IA para perfiles que necesitan confianza desde el primer vistazo',
      intro: 'En LinkedIn, la foto aparece en búsquedas de reclutadores, mensajes de networking, comentarios, invitaciones y páginas de empresa. En España y muchos mercados de Latinoamérica, una imagen clara puede ayudar a que el perfil parezca actualizado antes de una candidatura, una ronda comercial o un cambio de puesto. Esta página está pensada para crear una foto profesional sin convertirla en una sesión rígida: rostro reconocible, ropa adecuada para tu sector y un fondo que no robe atención.',
      primaryCta: 'Generar fotos para LinkedIn',
      secondaryCta: 'Ver ejemplos',
      casesTitle: 'Uso local para LinkedIn',
      casesText: 'Ajusta el estilo según cómo te van a descubrir: búsqueda, contacto comercial o perfil de experto.',
      cases: [
        { title: 'Búsqueda de reclutadores', text: 'Una foto nítida funciona mejor en vistas pequeñas y listas de candidatos.' },
        { title: 'Consultoría y ventas B2B', text: 'El retrato debe transmitir cercanía sin perder seriedad.' },
        { title: 'Fundadores y perfiles públicos', text: 'Útil para LinkedIn, bios de eventos y páginas de equipo.' },
      ],
      guidanceTitle: 'Guía específica para LinkedIn',
      guidanceText: 'Elige una imagen actual, fácil de reconocer y coherente con tu sector. Para perfiles técnicos o startup, un look smart-casual puede funcionar; para legal, finanzas o consultoría, conviene más formalidad.',
      checklist: ['Rostro visible y mirada directa', 'Ropa profesional o smart-casual', 'Fondo limpio con buen contraste', 'Expresión segura pero accesible'],
      linksTitle: 'Completa tu set profesional',
      linksText: 'Usa estos enlaces para adaptar la foto a CV, equipo o revisión visual.',
      relatedLinks: localizedRelated.es['ai-headshot-linkedin'],
      faqTitle: 'Preguntas sobre foto LinkedIn',
      faqText: 'Respuestas sobre estilo, fotos de origen y uso profesional.',
      faqs: [
        { question: '¿Sirve la misma foto para LinkedIn y bio de empresa?', answer: 'Sí, si el encuadre y el tono son profesionales. Puedes usar una versión más formal para web corporativa y otra más cercana para networking.' },
        { question: '¿Qué selfies debo subir?', answer: 'Sube fotos recientes, bien iluminadas y sin filtros fuertes. Varias tomas ayudan a conservar mejor el parecido.' },
        { question: '¿Debe ser muy formal?', answer: 'Depende del sector. Finanzas, legal y consultoría suelen pedir más formalidad; tecnología, producto o startups pueden aceptar un estilo más natural.' },
      ],
    },
    fr: {
      title: 'Photo LinkedIn IA pour profils professionnels',
      description: 'Créez une photo LinkedIn IA pour recruteurs, réseau, prospection et profils entreprise sans séance studio.',
      keywords: ['photo LinkedIn IA', 'portrait LinkedIn IA', 'photo professionnelle LinkedIn', 'portrait professionnel IA'],
      eyebrow: 'Usage LinkedIn',
      h1: 'Photo LinkedIn IA pour un profil crédible dès le premier contact',
      intro: 'Sur LinkedIn, la photo accompagne les recherches recruteur, les invitations, les commentaires, les messages de prospection et les pages entreprise. En France, en Belgique ou au Canada francophone, elle doit rester professionnelle sans donner l impression d une photo figée. Cette page aide à préparer un portrait clair, reconnaissable et adapté à un profil consultant, manager, fondateur ou candidat, avec un rendu utilisable aussi sur une bio courte, une signature ou une page équipe.',
      primaryCta: 'Générer des photos LinkedIn',
      secondaryCta: 'Voir les exemples',
      casesTitle: 'Contextes LinkedIn fréquents',
      casesText: 'Choisissez le style selon le moment où la photo sera vue.',
      cases: [
        { title: 'Recherche recruteur', text: 'Un visage net et bien cadré reste lisible dans les listes de profils.' },
        { title: 'Indépendants et consultants', text: 'Le portrait doit inspirer confiance sans paraître distant.' },
        { title: 'Fondateurs et managers', text: 'Utile pour LinkedIn, pages presse, événements et bios entreprise.' },
      ],
      guidanceTitle: 'Conseils pour LinkedIn',
      guidanceText: 'Privilégiez une image actuelle, sobre et facile à reconnaître. Les métiers conseil, finance et direction acceptent un rendu plus formel; les profils produit, design ou tech peuvent rester plus naturels.',
      checklist: ['Visage clair et regard direct', 'Tenue adaptée au secteur', 'Fond discret avec contraste', 'Expression ouverte et professionnelle'],
      linksTitle: 'Préparer les autres usages',
      linksText: 'Ces pages aident à décliner la photo pour CV, équipe ou comparaison.',
      relatedLinks: localizedRelated.fr['ai-headshot-linkedin'],
      faqTitle: 'Questions photo LinkedIn',
      faqText: 'Style, selfies source et usages professionnels.',
      faqs: [
        { question: 'Puis-je utiliser la même photo sur LinkedIn et une bio entreprise ?', answer: 'Oui, si le cadrage et le niveau de formalité conviennent aux deux supports. Une version plus sobre peut mieux fonctionner sur un site corporate.' },
        { question: 'Quelles photos importer ?', answer: 'Utilisez des selfies récents, bien éclairés, sans filtre fort. Plusieurs angles améliorent la stabilité de la ressemblance.' },
        { question: 'La photo doit-elle être très formelle ?', answer: 'Cela dépend du métier. Conseil, finance ou juridique demandent souvent plus de sobriété; tech et création peuvent tolérer un rendu plus chaleureux.' },
      ],
    },
    de: {
      title: 'KI Headshot für LinkedIn Profile',
      description: 'Erstelle einen realistischen KI Headshot für LinkedIn, Recruiter-Suche, Networking und Firmenprofile ohne Fotostudio.',
      keywords: ['LinkedIn Profilbild KI', 'KI Headshot LinkedIn', 'professionelles LinkedIn Foto', 'Business Profilbild KI'],
      eyebrow: 'LinkedIn Profilbild',
      h1: 'KI Headshot für LinkedIn Profile mit professionellem ersten Eindruck',
      intro: 'Ein LinkedIn Profilbild wird in der Recruiter-Suche, in Kontaktanfragen, Kommentaren, Sales-Nachrichten und auf Unternehmensseiten gesehen. Im DACH-Raum läuft berufliche Sichtbarkeit oft parallel über LinkedIn, Xing, Teamseiten und Bewerbungsunterlagen. Diese Seite hilft dir, ein aktuelles Bild zu planen, das seriös wirkt, aber nicht steif aussieht: klare Gesichtserkennung, passende Kleidung für Branche und Rolle, ein ruhiger Hintergrund und ein Ausdruck, der Vertrauen schafft.',
      primaryCta: 'LinkedIn Headshots generieren',
      secondaryCta: 'Beispiele ansehen',
      casesTitle: 'Typische LinkedIn-Situationen',
      casesText: 'Wähle den Stil danach, wo dein Profil zuerst wahrgenommen wird.',
      cases: [
        { title: 'Recruiter-Suche', text: 'Ein klares Gesicht bleibt auch in kleinen Profilkarten erkennbar.' },
        { title: 'B2B Vertrieb und Beratung', text: 'Der Look sollte zugänglich wirken, ohne zu locker zu sein.' },
        { title: 'Führungskräfte und Gründer', text: 'Geeignet für LinkedIn, Speaker-Bios, Presseprofile und Teamseiten.' },
      ],
      guidanceTitle: 'LinkedIn-spezifische Hinweise',
      guidanceText: 'Nutze ein aktuelles Bild mit ruhigem Hintergrund und direktem Blick. Für Beratung, Finance oder Recht passt ein formellerer Stil; für Produkt, Tech oder Startups darf es natürlicher sein.',
      checklist: ['Klares Gesicht und Blickkontakt', 'Business oder Smart-Casual Kleidung', 'Ruhiger Hintergrund mit Kontrast', 'Freundlicher, souveräner Ausdruck'],
      linksTitle: 'Weitere Profilbilder planen',
      linksText: 'Diese Seiten helfen bei Bewerbung, Teamseite und Qualitätsvergleich.',
      relatedLinks: localizedRelated.de['ai-headshot-linkedin'],
      faqTitle: 'Fragen zum LinkedIn Headshot',
      faqText: 'Antworten zu Stil, Uploads und beruflicher Nutzung.',
      faqs: [
        { question: 'Kann ich denselben Headshot auf LinkedIn und der Firmenbio nutzen?', answer: 'Ja. Achte nur darauf, dass Crop und Formalität zu beiden Kontexten passen.' },
        { question: 'Welche Selfies sollte ich hochladen?', answer: 'Aktuelle Fotos mit gutem Licht, sichtbarem Gesicht und ohne starke Filter funktionieren am besten.' },
        { question: 'Muss ein LinkedIn Foto formell sein?', answer: 'Nicht immer. In konservativen Branchen ist formeller besser, in Tech oder Startups kann ein natürlicher Business-Look glaubwürdiger sein.' },
      ],
    },
    ja: {
      title: 'LinkedIn用AIヘッドショット',
      description: 'LinkedIn、採用担当者の検索、営業プロフィール、企業ページ向けに自然なAIヘッドショットを作成します。',
      keywords: ['LinkedIn 写真 AI', 'AIヘッドショット LinkedIn', 'プロフィール写真 AI', '仕事用写真 AI'],
      eyebrow: 'LinkedInプロフィール向け',
      h1: '第一印象を整えるLinkedIn用AIヘッドショット',
      intro: 'LinkedInの写真は、採用担当者の検索、つながり申請、コメント欄、営業メッセージ、会社紹介ページなどで小さく表示されます。日本ではLinkedInだけでなく、Wantedly、Eight、会社サイト、登壇者プロフィールと並行して見られることもあります。このページは、今の自撮りが少しカジュアルすぎる、古い社員写真と印象が合わない、転職や商談前に公開プロフィールを整えたい人向けに、自然で信頼感のある写真を作るための案内です。',
      primaryCta: 'LinkedIn写真を生成',
      secondaryCta: 'サンプルを見る',
      casesTitle: 'LinkedInで使いやすい場面',
      casesText: 'どこで見られる写真なのかを決めると、表情や服装を選びやすくなります。',
      cases: [
        { title: '採用担当者の確認', text: '検索結果や候補者一覧でも顔がわかりやすい写真にします。' },
        { title: '営業とパートナー連絡', text: '堅すぎず、初回連絡でも安心感のある印象を作ります。' },
        { title: '登壇者や創業者プロフィール', text: 'LinkedIn、イベント紹介、会社ページで使える写真にします。' },
      ],
      guidanceTitle: 'LinkedIn向けの選び方',
      guidanceText: '顔がはっきり見え、背景が主張しすぎない写真が使いやすいです。金融、法律、コンサルでは少しフォーマルに、スタートアップやクリエイティブ職では自然な雰囲気でも問題ありません。',
      checklist: ['顔と目線がはっきりしている', '職種に合う服装', '背景がシンプルで見やすい', '近づきやすい自然な表情'],
      linksTitle: 'ほかの用途も準備する',
      linksText: '履歴書、社員紹介、サンプル確認に進めます。',
      relatedLinks: localizedRelated.ja['ai-headshot-linkedin'],
      faqTitle: 'LinkedIn写真の質問',
      faqText: '元写真、スタイル、公開プロフィールでの使い方について。',
      faqs: [
        { question: '同じ写真を会社プロフィールにも使えますか？', answer: '使えます。会社サイトでは少し落ち着いた表情や背景のほうが合う場合があります。' },
        { question: 'どんな写真をアップロードすればよいですか？', answer: '明るく、顔が隠れていない最近の自撮りを使ってください。複数の角度があると本人らしさが安定します。' },
        { question: 'LinkedIn写真はフォーマルであるべきですか？', answer: '職種によります。保守的な業界はフォーマルに、ITやスタートアップでは自然なビジネス写真でも使いやすいです。' },
      ],
    },
  },
  'ai-headshot-corporate': {
    en: {
      title: 'AI Corporate Headshots for Teams and Company Pages',
      description: 'Create AI corporate headshots for staff pages, team directories, sales profiles, and consistent business portraits.',
      keywords: ['AI corporate headshots', 'team headshot generator', 'business headshot AI', 'company profile photos'],
      eyebrow: 'Corporate team photo use case',
      h1: 'AI Corporate Headshots for Teams, Staff Pages, and Company Profiles',
      intro: 'Corporate headshots need consistency more than glamour. A team page with mixed crops, old photos, casual selfies, and different backgrounds can make even a strong company look improvised. This page is for founders, operators, HR teams, agencies, and sales leaders who need a practical visual direction for staff portraits. Use it before onboarding new employees, refreshing an about page, preparing proposal decks, or aligning distributed teams that cannot visit the same photographer on the same day.',
      primaryCta: 'Generate corporate headshots',
      secondaryCta: 'Review samples',
      casesTitle: 'Corporate scenarios this page supports',
      casesText: 'Use these cases to decide how formal, uniform, or approachable the team set should be.',
      cases: [
        { title: 'Team and about pages', text: 'Create a consistent visual language across employee portraits.' },
        { title: 'Sales and customer success', text: 'Give client-facing teams a polished image for proposals and email profiles.' },
        { title: 'Remote onboarding', text: 'Add new hires without waiting for everyone to attend a physical shoot.' },
      ],
      guidanceTitle: 'Corporate style rules',
      guidanceText: 'Decide the background, clothing range, crop, and expression before generating. Consistency across the set matters more than making every person look identical.',
      checklist: ['Shared crop and background direction', 'Business clothing range defined upfront', 'Enough contrast for staff directory thumbnails', 'Natural expression that matches company tone'],
      linksTitle: 'Extend the corporate set',
      linksText: 'Use related pages for LinkedIn alignment, studio formality, examples, and credits.',
      relatedLinks: englishRelated['ai-headshot-corporate'],
      faqTitle: 'Corporate headshot questions',
      faqText: 'Practical answers for team pages and business use.',
      faqs: [
        { question: 'Can remote employees use different source photos?', answer: 'Yes, but ask everyone for recent, clear selfies with similar lighting expectations so the final set feels more consistent.' },
        { question: 'Should all corporate headshots use the same background?', answer: 'A shared background direction helps, but small differences are fine if crop, lighting, and formality stay aligned.' },
        { question: 'Can these be used in proposals or company decks?', answer: 'Yes. Plans include commercial use for business profiles, websites, presentations, and public professional materials.' },
      ],
    },
    es: {
      title: 'Retratos corporativos con IA para equipos y empresa',
      description: 'Crea retratos corporativos con IA para páginas de equipo, ventas, propuestas y perfiles de empresa.',
      keywords: ['retratos corporativos IA', 'headshots equipo IA', 'foto empresa IA', 'retrato profesional empresa'],
      eyebrow: 'Caso de uso corporativo',
      h1: 'Retratos corporativos con IA para equipos, webs y perfiles de empresa',
      intro: 'Una página de equipo con fotos antiguas, fondos distintos y selfies casuales puede hacer que una empresa parezca menos organizada de lo que realmente es. En agencias, consultoras, SaaS, despachos o equipos comerciales distribuidos, la consistencia visual ayuda a presentar mejor a cada persona. Esta página sirve para definir una dirección de retrato corporativo antes de actualizar la web, incorporar nuevos empleados, preparar propuestas o unificar perfiles de LinkedIn sin coordinar una sesión presencial para todos.',
      primaryCta: 'Generar retratos corporativos',
      secondaryCta: 'Ver muestras',
      casesTitle: 'Escenarios corporativos',
      casesText: 'Define si el equipo necesita un look formal, cercano o mixto.',
      cases: [
        { title: 'Página de equipo', text: 'Unifica encuadre, fondo y tono para que la web parezca cuidada.' },
        { title: 'Ventas y customer success', text: 'Da a los perfiles de cara al cliente una imagen más confiable.' },
        { title: 'Equipos remotos', text: 'Añade nuevas incorporaciones sin esperar una sesión fotográfica común.' },
      ],
      guidanceTitle: 'Reglas de estilo corporativo',
      guidanceText: 'Decide fondo, ropa, encuadre y expresión antes de generar. La consistencia importa más que hacer que todas las personas se vean idénticas.',
      checklist: ['Encuadre compartido', 'Ropa profesional definida', 'Contraste para miniaturas', 'Expresión natural acorde a la marca'],
      linksTitle: 'Amplía el set corporativo',
      linksText: 'Estos enlaces ayudan a coordinar LinkedIn, estilo estudio, muestras y créditos.',
      relatedLinks: localizedRelated.es['ai-headshot-corporate'],
      faqTitle: 'Preguntas de retrato corporativo',
      faqText: 'Uso para equipos, web y materiales comerciales.',
      faqs: [
        { question: '¿Pueden subir fotos distintas los empleados remotos?', answer: 'Sí. Pide selfies recientes, nítidos y con iluminación similar para que el resultado tenga coherencia.' },
        { question: '¿Debe ser el mismo fondo para todos?', answer: 'Ayuda mucho, pero no es obligatorio si el encuadre, la luz y la formalidad se mantienen alineados.' },
        { question: '¿Sirve para propuestas y decks?', answer: 'Sí. Los planes permiten uso comercial en webs, perfiles, presentaciones y materiales profesionales.' },
      ],
    },
    fr: {
      title: 'Portraits corporate IA pour équipes et pages entreprise',
      description: 'Créez des portraits corporate IA pour pages équipe, profils commerciaux, annuaires et supports entreprise.',
      keywords: ['portraits corporate IA', 'headshots equipe IA', 'photo entreprise IA', 'portrait business IA'],
      eyebrow: 'Usage corporate',
      h1: 'Portraits corporate IA pour équipes, sites et profils entreprise',
      intro: 'Une page équipe avec des cadrages différents, des photos trop anciennes et des arrière-plans incohérents peut donner une impression moins professionnelle que l entreprise elle-même. Pour une agence, un cabinet de conseil, une ESN, une startup B2B ou une équipe commerciale répartie, la cohérence visuelle aide à présenter les personnes clairement. Cette page sert à définir une direction de portrait avant une refonte de site, une proposition client, une arrivée collaborateur ou une harmonisation LinkedIn.',
      primaryCta: 'Générer des portraits corporate',
      secondaryCta: 'Voir les exemples',
      casesTitle: 'Scénarios corporate',
      casesText: 'Choisissez le niveau de formalité selon le rôle public de l équipe.',
      cases: [
        { title: 'Page équipe', text: 'Unifiez cadrage, fond et niveau de tenue pour une page plus crédible.' },
        { title: 'Vente et relation client', text: 'Donnez aux profils exposés une image claire et rassurante.' },
        { title: 'Équipes distribuées', text: 'Ajoutez de nouvelles personnes sans organiser une séance commune.' },
      ],
      guidanceTitle: 'Règles de style corporate',
      guidanceText: 'Décidez le fond, la tenue, le cadrage et l expression avant de générer. Une cohérence lisible compte plus qu une uniformité excessive.',
      checklist: ['Cadrage commun', 'Tenue professionnelle définie', 'Contraste lisible en annuaire', 'Expression naturelle alignée à la marque'],
      linksTitle: 'Compléter le set corporate',
      linksText: 'Ces liens aident à gérer LinkedIn, le style studio, les exemples et les crédits.',
      relatedLinks: localizedRelated.fr['ai-headshot-corporate'],
      faqTitle: 'Questions portrait corporate',
      faqText: 'Réponses pour pages équipe, supports commerciaux et usage entreprise.',
      faqs: [
        { question: 'Les collaborateurs distants peuvent-ils importer des photos différentes ?', answer: 'Oui, mais demandez des selfies récents, nets et bien éclairés pour garder une cohérence visuelle.' },
        { question: 'Faut-il exactement le même fond ?', answer: 'Un fond commun aide, mais le cadrage, la lumière et le niveau de formalité sont souvent plus importants.' },
        { question: 'Peut-on utiliser ces portraits dans des présentations ?', answer: 'Oui. Les plans couvrent les sites, profils publics, présentations et supports professionnels.' },
      ],
    },
    de: {
      title: 'KI Corporate Headshots für Teams und Firmenprofile',
      description: 'Erstelle KI Corporate Headshots für Teamseiten, Verzeichnisse, Sales-Profile und Business-Unterlagen.',
      keywords: ['Corporate Headshots KI', 'Team Headshot Generator', 'Business Headshot KI', 'Firmenprofil Fotos'],
      eyebrow: 'Corporate Teamfotos',
      h1: 'KI Corporate Headshots für Teams, Mitarbeiterseiten und Firmenprofile',
      intro: 'Eine Teamseite mit alten Bildern, unterschiedlichen Hintergründen und zufälligen Selfies wirkt schnell weniger professionell als das Unternehmen selbst. In DACH-Kontexten wie Beratung, Kanzlei, SaaS, Agentur oder Mittelstand zählt eine klare und seriöse Außendarstellung. Diese Seite hilft, vor einer Website-Aktualisierung, einem Pitchdeck, einem neuen Mitarbeiterprofil oder einer LinkedIn-Harmonisierung eine gemeinsame Richtung für Business-Portraits festzulegen.',
      primaryCta: 'Corporate Headshots generieren',
      secondaryCta: 'Beispiele prüfen',
      casesTitle: 'Corporate Einsatzbereiche',
      casesText: 'Lege fest, ob das Team formeller, zugänglicher oder einheitlicher erscheinen soll.',
      cases: [
        { title: 'Teamseite und Über uns', text: 'Vereinheitliche Crop, Hintergrund und Professionalität der Mitarbeiterbilder.' },
        { title: 'Sales und Beratung', text: 'Client-facing Teams erhalten ein vertrauenswürdiges Bild für Angebote und E-Mail-Profile.' },
        { title: 'Remote Onboarding', text: 'Neue Mitarbeitende lassen sich ergänzen, ohne einen gemeinsamen Fototermin zu planen.' },
      ],
      guidanceTitle: 'Corporate Stilregeln',
      guidanceText: 'Entscheide Hintergrund, Kleidung, Crop und Ausdruck vorab. Wiedererkennbare Konsistenz ist wichtiger als perfekte Gleichförmigkeit.',
      checklist: ['Gemeinsamer Bildausschnitt', 'Definierte Business-Kleidung', 'Kontrast für Mitarbeiterverzeichnisse', 'Natürlicher Ausdruck passend zur Marke'],
      linksTitle: 'Corporate Set erweitern',
      linksText: 'Diese Seiten helfen bei LinkedIn, Studio-Stil, Beispielen und Credits.',
      relatedLinks: localizedRelated.de['ai-headshot-corporate'],
      faqTitle: 'Fragen zu Corporate Headshots',
      faqText: 'Antworten für Teamseiten, Pitchdecks und Firmenprofile.',
      faqs: [
        { question: 'Können Remote-Mitarbeiter unterschiedliche Fotos hochladen?', answer: 'Ja. Klare, aktuelle Selfies mit ähnlicher Lichtqualität helfen, ein konsistentes Ergebnis zu erzeugen.' },
        { question: 'Brauchen alle denselben Hintergrund?', answer: 'Ein gemeinsamer Hintergrund hilft, aber Crop, Licht und Formalität sind oft wichtiger.' },
        { question: 'Dürfen wir die Headshots in Präsentationen nutzen?', answer: 'Ja. Die Ergebnisse können für Websites, Profile, Präsentationen und professionelle Materialien genutzt werden.' },
      ],
    },
    ja: {
      title: '企業向けAIヘッドショット',
      description: '社員紹介、会社サイト、営業プロフィール、提案資料に使える企業向けAIヘッドショットを作成します。',
      keywords: ['企業写真 AI', '社員紹介 写真 AI', 'AIヘッドショット 企業', 'ビジネス写真 AI'],
      eyebrow: '企業・チーム向け',
      h1: '社員紹介と会社ページに使える企業向けAIヘッドショット',
      intro: '社員紹介ページに古い写真、背景の違う写真、カジュアルな自撮りが混ざっていると、会社の印象までばらついて見えます。日本の採用ページ、営業資料、会社案内、Wantedlyやコーポレートサイトでは、写真の統一感が信頼感につながります。このページは、新入社員の追加、サイト更新、提案資料、分散チームのプロフィール整備に合わせて、同じ方向性の仕事用写真を作りたい場合に使えます。',
      primaryCta: '企業向け写真を生成',
      secondaryCta: 'サンプルを見る',
      casesTitle: '企業で使いやすい場面',
      casesText: 'チームの印象をフォーマルにするか、親しみやすくするかを決めます。',
      cases: [
        { title: '社員紹介ページ', text: '構図、背景、服装の印象をそろえて見やすくします。' },
        { title: '営業・カスタマーサクセス', text: '顧客に見られるプロフィールを信頼感のある写真にします。' },
        { title: 'リモート採用', text: '同じ撮影日に集まれないメンバーも追加しやすくなります。' },
      ],
      guidanceTitle: '企業写真の決め方',
      guidanceText: '背景、服装、構図、表情を先に決めると統一感が出ます。全員を同じ顔つきにする必要はなく、会社らしいトーンに合わせることが大切です。',
      checklist: ['共通の構図', '仕事に合う服装ルール', '一覧でも見やすいコントラスト', '会社の雰囲気に合う自然な表情'],
      linksTitle: '企業写真セットを広げる',
      linksText: 'LinkedIn、スタジオ風、サンプル、料金を確認できます。',
      relatedLinks: localizedRelated.ja['ai-headshot-corporate'],
      faqTitle: '企業向け写真の質問',
      faqText: '社員紹介、営業資料、会社ページでの使い方について。',
      faqs: [
        { question: 'リモート社員が別々の写真を使ってもよいですか？', answer: 'はい。明るく顔が見える最近の写真を用意してもらうと、仕上がりの統一感が出やすくなります。' },
        { question: '背景は全員同じにするべきですか？', answer: '同じ方向性にすると見やすいですが、構図、明るさ、フォーマル度が合っていれば問題ありません。' },
        { question: '提案資料や会社案内にも使えますか？', answer: '使えます。ビジネスプロフィール、会社サイト、資料などの商用利用に対応しています。' },
      ],
    },
  },
  'ai-headshot-resume': {
    en: {
      title: 'AI Resume Photo Generator for CVs and Applications',
      description: 'Create a restrained AI resume photo for CVs, applications, portfolios, and professional profiles when a photo is appropriate.',
      keywords: ['AI resume photo generator', 'AI CV photo', 'professional resume photo', 'application photo AI'],
      eyebrow: 'Resume and CV photo use case',
      h1: 'AI Resume Photo Generator for CVs, Applications, and Professional Profiles',
      intro: 'A resume photo is not always expected, especially in the United States, but many professionals still need a restrained portrait for CV markets, portfolio profiles, internal mobility pages, academic bios, or application portals that request an image. This page is built for people who want a photo that supports the document instead of overpowering it. The goal is simple: look current, clear, and professional, with a calm expression and styling that does not distract from your experience, skills, and role fit.',
      primaryCta: 'Generate resume photos',
      secondaryCta: 'See resume examples',
      casesTitle: 'When a resume-style image is useful',
      casesText: 'Use this direction when the photo needs to feel more document-ready than social-profile oriented.',
      cases: [
        { title: 'International CVs', text: 'Use a clean portrait for markets or portals where a CV photo is common.' },
        { title: 'Portfolio and academic bios', text: 'Keep the image professional without making the page feel like a personal brand campaign.' },
        { title: 'Internal applications', text: 'Use a current photo for employee profiles, internal mobility, and professional directories.' },
      ],
      guidanceTitle: 'Resume photo guidance',
      guidanceText: 'A resume-style headshot should be quieter than a marketing portrait. Choose neutral clothing, a simple crop, and a background that lets the document stay the focus.',
      checklist: ['Calm expression and direct face view', 'Simple clothing without loud patterns', 'Neutral background and conservative crop', 'Current likeness that matches interviews and profiles'],
      linksTitle: 'Adapt this photo for other channels',
      linksText: 'A resume photo can also feed your LinkedIn, bio, and sample review workflow.',
      relatedLinks: englishRelated['ai-headshot-resume'],
      faqTitle: 'AI resume photo questions',
      faqText: 'How to use a resume-style portrait without making the document feel overdone.',
      faqs: [
        { question: 'Should I put a photo on every resume?', answer: 'No. Use a resume photo only when it is expected in your market, requested by a portal, or appropriate for a CV, bio, or portfolio context.' },
        { question: 'What style works best for a resume photo?', answer: 'Choose a restrained business look with a neutral background, clear face, and minimal styling.' },
        { question: 'Can I use the same image on LinkedIn?', answer: 'Yes, but LinkedIn can tolerate a slightly warmer expression and tighter crop than a conservative resume photo.' },
      ],
    },
    es: {
      title: 'Generador de foto para CV con IA',
      description: 'Crea una foto profesional para CV, candidaturas, portafolios y perfiles cuando tu mercado la espera.',
      keywords: ['foto CV IA', 'generador foto curriculum IA', 'foto profesional CV', 'foto candidatura IA'],
      eyebrow: 'Caso de uso para CV',
      h1: 'Generador de foto para CV con IA para candidaturas y perfiles profesionales',
      intro: 'En algunos mercados hispanohablantes la foto en el CV sigue siendo habitual, mientras que en otros puede no ser recomendable. Por eso esta página no busca imponer una regla, sino ayudar cuando sí necesitas una imagen: portales de empleo, CV europeo, bio académica, portafolio, perfil interno o candidatura donde el formato la solicita. El objetivo es una foto sobria, actual y reconocible, que acompañe tu experiencia sin robar protagonismo al contenido del currículum.',
      primaryCta: 'Generar foto para CV',
      secondaryCta: 'Ver ejemplos',
      casesTitle: 'Cuándo usar una foto tipo CV',
      casesText: 'Elige este estilo cuando la imagen debe apoyar el documento, no parecer una campaña personal.',
      cases: [
        { title: 'CV con foto', text: 'Útil en mercados o portales donde el formato la solicita.' },
        { title: 'Portafolio y bio', text: 'Mantiene una imagen profesional sin parecer demasiado promocional.' },
        { title: 'Perfil interno', text: 'Sirve para movilidad interna, directorios y documentación de empresa.' },
      ],
      guidanceTitle: 'Guía para foto de CV',
      guidanceText: 'Una foto de CV debe ser más discreta que una foto de LinkedIn. Usa ropa simple, expresión calmada y fondo neutral para que el documento siga siendo el protagonista.',
      checklist: ['Expresión tranquila', 'Ropa sin estampados fuertes', 'Fondo neutro', 'Parecido actual y reconocible'],
      linksTitle: 'Adapta la foto a otros canales',
      linksText: 'Puedes usar el mismo set para LinkedIn, bio o revisión de muestras.',
      relatedLinks: localizedRelated.es['ai-headshot-resume'],
      faqTitle: 'Preguntas sobre foto para CV',
      faqText: 'Cuándo usarla y cómo mantenerla profesional.',
      faqs: [
        { question: '¿Debo poner foto en todos los CV?', answer: 'No. Úsala solo cuando tu mercado, portal o formato la espera. En algunos países puede no ser conveniente.' },
        { question: '¿Qué estilo funciona mejor?', answer: 'Un retrato sobrio, con fondo limpio, rostro claro y ropa profesional sin elementos llamativos.' },
        { question: '¿Puedo usarla también en LinkedIn?', answer: 'Sí, aunque para LinkedIn puede funcionar una expresión un poco más cercana y un encuadre más visible.' },
      ],
    },
    fr: {
      title: 'Générateur de photo CV IA',
      description: 'Créez une photo sobre pour CV, candidatures, portfolios et profils professionnels quand le contexte le demande.',
      keywords: ['photo CV IA', 'generateur photo CV IA', 'photo candidature IA', 'portrait CV professionnel'],
      eyebrow: 'Usage CV et candidature',
      h1: 'Générateur de photo CV IA pour candidatures, bios et profils professionnels',
      intro: 'La photo sur un CV dépend du pays, du secteur et du format demandé. En France, elle reste fréquente dans certains contextes, mais elle doit rester sobre et ne pas détourner l attention du parcours. Cette page aide lorsque vous avez besoin d une image pour un CV, un profil Welcome to the Jungle, une bio académique, un portfolio, une candidature internationale ou un annuaire interne. Le but est un portrait clair, actuel et discret, qui soutient le dossier sans le transformer en publicité personnelle.',
      primaryCta: 'Générer une photo CV',
      secondaryCta: 'Voir les exemples',
      casesTitle: 'Quand utiliser une photo type CV',
      casesText: 'Choisissez ce style quand la photo doit rester secondaire par rapport au contenu.',
      cases: [
        { title: 'CV avec photo', text: 'Adapté aux formats ou marchés qui attendent une image.' },
        { title: 'Portfolio et bio', text: 'Donne un visage professionnel sans ton trop promotionnel.' },
        { title: 'Annuaire interne', text: 'Utile pour mobilité interne, pages équipe et profils collaborateurs.' },
      ],
      guidanceTitle: 'Conseils photo CV',
      guidanceText: 'Une photo de CV doit rester plus discrète qu une photo de profil social. Fond neutre, tenue simple, expression calme et cadrage propre suffisent.',
      checklist: ['Expression posée', 'Tenue simple et professionnelle', 'Fond neutre', 'Ressemblance actuelle'],
      linksTitle: 'Décliner la photo ailleurs',
      linksText: 'La même génération peut servir à LinkedIn, bio et comparaison de résultats.',
      relatedLinks: localizedRelated.fr['ai-headshot-resume'],
      faqTitle: 'Questions photo CV',
      faqText: 'Usage, style et adaptation aux candidatures.',
      faqs: [
        { question: 'Faut-il mettre une photo sur tous les CV ?', answer: 'Non. Utilisez-la seulement si le marché, le portail ou le format la demande ou la rend pertinente.' },
        { question: 'Quel style choisir ?', answer: 'Un portrait sobre avec fond propre, visage clair et tenue professionnelle.' },
        { question: 'Puis-je l utiliser sur LinkedIn ?', answer: 'Oui, mais LinkedIn peut accepter une expression un peu plus chaleureuse et un cadrage plus serré.' },
      ],
    },
    de: {
      title: 'KI Bewerbungsfoto für Lebenslauf und Bewerbung',
      description: 'Erstelle ein zurückhaltendes KI Bewerbungsfoto für Lebenslauf, CV, Portale und professionelle Profile.',
      keywords: ['KI Bewerbungsfoto', 'Lebenslauf Foto KI', 'Bewerbungsfoto Generator', 'professionelles Bewerbungsfoto KI'],
      eyebrow: 'Bewerbungsfoto und Lebenslauf',
      h1: 'KI Bewerbungsfoto für Lebenslauf, CV und berufliche Profile',
      intro: 'Im DACH-Raum ist ein Bewerbungsfoto je nach Branche, Unternehmen und Bewerbungsformat weiterhin relevant, auch wenn es nicht überall Pflicht ist. Diese Seite hilft, wenn du ein seriöses Bild für Lebenslauf, Xing, LinkedIn, Bewerbungsportal, akademische Bio oder internes Profil brauchst. Das Foto soll den Lebenslauf unterstützen, nicht dominieren: aktuelles Aussehen, ruhiger Hintergrund, klare Gesichtserkennung und ein Ausdruck, der professionell wirkt, ohne steif oder überinszeniert zu sein.',
      primaryCta: 'Bewerbungsfoto generieren',
      secondaryCta: 'Beispiele ansehen',
      casesTitle: 'Wann ein Bewerbungsfoto sinnvoll ist',
      casesText: 'Nutze diesen Stil, wenn das Bild dokumentennah und zurückhaltend wirken soll.',
      cases: [
        { title: 'Lebenslauf und CV', text: 'Geeignet für Bewerbungsformate, in denen ein Foto üblich ist.' },
        { title: 'Xing und Portale', text: 'Ein ruhiges Bild wirkt auch in beruflichen Verzeichnissen passend.' },
        { title: 'Interne Profile', text: 'Nützlich für Mitarbeiterverzeichnisse und interne Mobilität.' },
      ],
      guidanceTitle: 'Hinweise zum Bewerbungsfoto',
      guidanceText: 'Ein Bewerbungsfoto sollte reduzierter sein als ein Marketing-Portrait. Wähle neutrale Kleidung, einen klaren Hintergrund und eine freundliche, ruhige Mimik.',
      checklist: ['Ruhiger Ausdruck', 'Schlichte Business-Kleidung', 'Neutraler Hintergrund', 'Aktuelle Wiedererkennbarkeit'],
      linksTitle: 'Für weitere Kanäle anpassen',
      linksText: 'Nutze verwandte Seiten für LinkedIn, Bio und Qualitätsvergleich.',
      relatedLinks: localizedRelated.de['ai-headshot-resume'],
      faqTitle: 'Fragen zum KI Bewerbungsfoto',
      faqText: 'Antworten zu Lebenslauf, Stil und Profilnutzung.',
      faqs: [
        { question: 'Braucht jeder Lebenslauf ein Foto?', answer: 'Nein. Nutze es, wenn es in deinem Markt oder Format erwartet wird oder für ein berufliches Profil sinnvoll ist.' },
        { question: 'Welcher Stil passt am besten?', answer: 'Ein ruhiges Business-Portrait mit neutralem Hintergrund, klarem Gesicht und wenig Ablenkung.' },
        { question: 'Kann ich dasselbe Foto auf LinkedIn nutzen?', answer: 'Ja. Für LinkedIn darf die Version etwas wärmer und präsenter sein als im Lebenslauf.' },
      ],
    },
    ja: {
      title: '履歴書向けAI写真ジェネレーター',
      description: '履歴書、職務経歴書、応募フォーム、社内プロフィール向けに落ち着いたAI写真を作成します。',
      keywords: ['履歴書 写真 AI', '職務経歴書 写真 AI', '証明写真 AI', '応募写真 AI'],
      eyebrow: '履歴書・応募書類向け',
      h1: '履歴書や職務経歴書に使いやすいAI写真ジェネレーター',
      intro: '日本の履歴書や応募フォームでは、写真が必要になる場面がまだ多くあります。ただし、SNS向けの華やかな写真ではなく、書類全体の印象を邪魔しない落ち着いた写真が向いています。このページは、履歴書、職務経歴書、転職サービス、社内プロフィール、資格申請などに使える、現在の本人らしさが伝わる写真を準備したい人向けです。背景は控えめに、服装は職種に合わせ、表情は自然で誠実に見える方向を選びます。',
      primaryCta: '履歴書写真を生成',
      secondaryCta: '例を見る',
      casesTitle: '履歴書向け写真が必要な場面',
      casesText: '書類の内容を引き立てる、落ち着いた写真を選びます。',
      cases: [
        { title: '履歴書と応募フォーム', text: '指定された形式で使いやすい写真を準備します。' },
        { title: '職務経歴や資格プロフィール', text: '実績や経歴を邪魔しない自然な印象にします。' },
        { title: '社内プロフィール', text: '異動、社内公募、社員紹介にも使いやすい写真です。' },
      ],
      guidanceTitle: '履歴書写真の選び方',
      guidanceText: '表情は穏やかに、背景はシンプルにします。派手な服装や強い加工よりも、本人とわかる自然さを優先します。',
      checklist: ['落ち着いた表情', 'シンプルな服装', '控えめな背景', '面接時と違和感のない本人らしさ'],
      linksTitle: 'ほかのプロフィールにも使う',
      linksText: 'LinkedIn、仕事用プロフィール、FAQ、サンプルを確認できます。',
      relatedLinks: localizedRelated.ja['ai-headshot-resume'],
      faqTitle: '履歴書写真の質問',
      faqText: '応募書類での使い方と写真の選び方について。',
      faqs: [
        { question: 'すべての応募で写真が必要ですか？', answer: '必要とは限りません。応募先や提出フォーマットで求められる場合に使ってください。' },
        { question: 'どんなスタイルがよいですか？', answer: '背景が控えめで、顔が明るく見え、服装が職種に合っている写真が使いやすいです。' },
        { question: 'LinkedInにも同じ写真を使えますか？', answer: '使えます。LinkedInでは少し親しみやすい表情の別バージョンも合います。' },
      ],
    },
  },
  'ai-headshot-studio-style': {
    en: {
      title: 'AI Studio Style Headshots Without a Photo Shoot',
      description: 'Generate studio-style AI headshots with polished lighting, clean backgrounds, and professional portrait direction.',
      keywords: ['AI studio headshot', 'studio style AI portrait', 'professional studio headshot AI', 'AI portrait studio'],
      eyebrow: 'Studio-style portrait use case',
      h1: 'AI Studio Style Headshots Without Scheduling a Photo Shoot',
      intro: 'A studio-style headshot is useful when the image needs more polish than a casual profile photo but you do not want the cost, timing, or logistics of a photographer. This page focuses on clean lighting, simple backgrounds, balanced contrast, and a portrait style that feels suitable for executive bios, consulting profiles, speaker pages, press kits, and premium service pages. Use it when your brand needs a composed look, your old headshot has uneven lighting, or your public profile should feel more deliberate.',
      primaryCta: 'Generate studio-style headshots',
      secondaryCta: 'Compare samples',
      casesTitle: 'Studio-style scenarios',
      casesText: 'Choose this direction when visual polish and controlled lighting matter.',
      cases: [
        { title: 'Executive bios', text: 'A composed image works well for leadership pages and press profiles.' },
        { title: 'Consulting and premium services', text: 'Clean studio direction supports trust for high-consideration services.' },
        { title: 'Speaker and media kits', text: 'Use a portrait that feels intentional in event pages and introductions.' },
      ],
      guidanceTitle: 'How to keep it realistic',
      guidanceText: 'Studio style should not mean plastic. Pick simple backgrounds, realistic wardrobe, and lighting that supports your face rather than hiding it.',
      checklist: ['Soft, controlled lighting', 'Simple background with professional tone', 'Wardrobe that matches the service level', 'Natural skin texture and recognizable likeness'],
      linksTitle: 'Compare formal and flexible options',
      linksText: 'Use these pages to decide whether a studio, corporate, or general professional image fits best.',
      relatedLinks: englishRelated['ai-headshot-studio-style'],
      faqTitle: 'Studio-style AI headshot questions',
      faqText: 'How to get polished results without making the portrait look artificial.',
      faqs: [
        { question: 'Is a studio-style AI headshot different from a corporate headshot?', answer: 'Studio-style focuses on polished lighting and controlled backgrounds. Corporate headshots focus more on consistency across a team.' },
        { question: 'Will it look overly retouched?', answer: 'It should not. Use clear source photos and choose realistic styles so skin texture, expression, and likeness remain natural.' },
        { question: 'Where should I use a studio-style headshot?', answer: 'It works well for executive bios, consultant profiles, speaker pages, premium service pages, and press materials.' },
      ],
    },
    es: {
      title: 'Headshots estilo estudio con IA',
      description: 'Genera retratos estilo estudio con IA: luz cuidada, fondos limpios y dirección profesional sin sesión fotográfica.',
      keywords: ['headshot estilo estudio IA', 'retrato estudio IA', 'foto profesional estudio IA', 'portrait studio IA'],
      eyebrow: 'Caso de uso estilo estudio',
      h1: 'Headshots estilo estudio con IA sin reservar una sesión fotográfica',
      intro: 'Un retrato estilo estudio funciona cuando necesitas más pulido que una foto de perfil casual, pero no quieres coordinar agenda, fotógrafo, desplazamiento y selección de fotos. En consultoría, real estate, coaching, dirección, finanzas o servicios premium, la luz limpia y el fondo controlado ayudan a presentar una imagen más deliberada. Esta página se centra en un resultado elegante pero realista: rostro reconocible, textura natural, ropa acorde al servicio y una composición que pueda usarse en bios, webs y materiales comerciales.',
      primaryCta: 'Generar estilo estudio',
      secondaryCta: 'Ver ejemplos',
      casesTitle: 'Cuándo elegir estilo estudio',
      casesText: 'Úsalo cuando la luz, el fondo y la formalidad importan más que la espontaneidad.',
      cases: [
        { title: 'Directivos y fundadores', text: 'Aporta presencia para bios, prensa y páginas de liderazgo.' },
        { title: 'Servicios premium', text: 'Funciona para consultoría, legal, finanzas, coaching y real estate.' },
        { title: 'Eventos y ponencias', text: 'Da una foto más cuidada para programas, invitaciones y media kits.' },
      ],
      guidanceTitle: 'Mantenerlo realista',
      guidanceText: 'El estilo estudio no debe parecer artificial. Elige fondos simples, ropa creíble y luz que favorezca el rostro sin borrar la textura natural.',
      checklist: ['Luz suave y controlada', 'Fondo limpio', 'Ropa alineada al servicio', 'Piel natural y parecido reconocible'],
      linksTitle: 'Compara opciones formales y flexibles',
      linksText: 'Decide si necesitas estudio, corporativo o una foto profesional general.',
      relatedLinks: localizedRelated.es['ai-headshot-studio-style'],
      faqTitle: 'Preguntas sobre estilo estudio',
      faqText: 'Cómo lograr un resultado pulido sin parecer artificial.',
      faqs: [
        { question: '¿Es diferente de un retrato corporativo?', answer: 'Sí. El estilo estudio prioriza luz y fondo pulidos; el corporativo prioriza consistencia para equipos.' },
        { question: '¿Puede verse demasiado retocado?', answer: 'No debería. Usa selfies claros y estilos realistas para conservar textura, expresión y parecido.' },
        { question: '¿Dónde conviene usarlo?', answer: 'En bios directivas, servicios premium, ponencias, prensa, webs profesionales y presentaciones.' },
      ],
    },
    fr: {
      title: 'Portrait style studio IA sans séance photo',
      description: 'Générez des portraits IA style studio avec lumière soignée, fond propre et rendu professionnel.',
      keywords: ['portrait studio IA', 'headshot studio IA', 'photo professionnelle studio IA', 'portrait IA premium'],
      eyebrow: 'Usage style studio',
      h1: 'Portrait style studio IA sans organiser de séance photo',
      intro: 'Un portrait style studio est utile lorsque l image doit être plus soignée qu une photo de profil classique, sans bloquer une demi-journée de prise de vue. Pour un dirigeant, consultant, avocat, coach, expert B2B ou intervenant événementiel, une lumière propre et un fond maîtrisé donnent une impression plus posée. Cette page aide à obtenir un rendu élégant mais crédible, avec un visage reconnaissable, une texture naturelle et une tenue compatible avec le niveau de service ou de responsabilité.',
      primaryCta: 'Générer un style studio',
      secondaryCta: 'Voir les exemples',
      casesTitle: 'Quand choisir le style studio',
      casesText: 'Utile lorsque la maîtrise visuelle compte plus que l effet spontané.',
      cases: [
        { title: 'Dirigeants et fondateurs', text: 'Un rendu posé pour bios, presse et pages leadership.' },
        { title: 'Services premium', text: 'Adapté au conseil, juridique, finance, coaching et B2B.' },
        { title: 'Conférences et médias', text: 'Une image propre pour programmes, introductions et kits presse.' },
      ],
      guidanceTitle: 'Garder un rendu réaliste',
      guidanceText: 'Le style studio ne doit pas effacer la personne. Préférez des fonds simples, une tenue crédible et une lumière qui valorise le visage sans le lisser excessivement.',
      checklist: ['Lumière douce et contrôlée', 'Fond simple', 'Tenue alignée au contexte', 'Texture naturelle et ressemblance'],
      linksTitle: 'Comparer les options',
      linksText: 'Décidez entre studio, corporate et photo professionnelle polyvalente.',
      relatedLinks: localizedRelated.fr['ai-headshot-studio-style'],
      faqTitle: 'Questions style studio',
      faqText: 'Obtenir un rendu soigné sans effet artificiel.',
      faqs: [
        { question: 'Est-ce différent d un portrait corporate ?', answer: 'Oui. Le style studio vise surtout la lumière et le fond; le corporate vise la cohérence d équipe.' },
        { question: 'Le résultat sera-t-il trop retouché ?', answer: 'Pas si les photos sources sont claires et si vous choisissez un style réaliste.' },
        { question: 'Où utiliser ce portrait ?', answer: 'Sur bios dirigeants, pages conseil, conférences, presse, services premium et présentations.' },
      ],
    },
    de: {
      title: 'KI Studio Headshots ohne Fototermin',
      description: 'Generiere Studio-Style KI Headshots mit sauberem Licht, ruhigem Hintergrund und professioneller Portraitwirkung.',
      keywords: ['KI Studio Headshot', 'Studio Portrait KI', 'professionelles Studiofoto KI', 'KI Portrait Studio'],
      eyebrow: 'Studio-Stil',
      h1: 'KI Studio Headshots ohne Fototermin im Studio',
      intro: 'Ein Studio-Headshot ist sinnvoll, wenn das Bild hochwertiger wirken soll als ein normales Profilfoto, aber ein echter Fototermin zu aufwendig ist. Für Führungskräfte, Consultants, Kanzleiprofile, Coaches, Speaker und Premium-Dienstleister zählt ein kontrollierter Look mit sauberem Licht und ruhigem Hintergrund. Diese Seite hilft, ein Bild zu erzeugen, das bewusst und professionell wirkt, ohne künstlich zu erscheinen: erkennbare Ähnlichkeit, natürliche Hautstruktur, passende Kleidung und ein Bildaufbau, der für Website, Bio und Präsentationen funktioniert.',
      primaryCta: 'Studio-Headshots generieren',
      secondaryCta: 'Beispiele ansehen',
      casesTitle: 'Wann Studio-Stil passt',
      casesText: 'Wähle diesen Stil, wenn Licht, Hintergrund und Formalität wichtig sind.',
      cases: [
        { title: 'Executive Bios', text: 'Ein kontrolliertes Bild passt zu Führung, Presse und Unternehmensprofilen.' },
        { title: 'Beratung und Premium-Services', text: 'Der Look unterstützt Vertrauen bei erklärungsbedürftigen Leistungen.' },
        { title: 'Speaker und Medien', text: 'Ein sauberes Portrait wirkt in Programmen und Media Kits professionell.' },
      ],
      guidanceTitle: 'Realistisch bleiben',
      guidanceText: 'Studio-Stil sollte nicht nach Retusche aussehen. Nutze klare Ausgangsfotos und wähle Licht, Kleidung und Hintergrund glaubwürdig.',
      checklist: ['Weiches, kontrolliertes Licht', 'Ruhiger professioneller Hintergrund', 'Kleidung passend zum Kontext', 'Natürliche Hautstruktur und Wiedererkennbarkeit'],
      linksTitle: 'Formell oder flexibel vergleichen',
      linksText: 'Diese Seiten helfen bei Studio, Corporate und allgemeiner Profilfoto-Wahl.',
      relatedLinks: localizedRelated.de['ai-headshot-studio-style'],
      faqTitle: 'Fragen zum Studio-Headshot',
      faqText: 'So bleibt der Look hochwertig, aber natürlich.',
      faqs: [
        { question: 'Ist Studio-Stil anders als Corporate?', answer: 'Ja. Studio-Stil priorisiert Licht und Hintergrund, Corporate priorisiert Konsistenz über ein Team hinweg.' },
        { question: 'Wirkt das Ergebnis zu stark retuschiert?', answer: 'Das sollte es nicht. Gute Ausgangsfotos und realistische Stile halten Haut, Ausdruck und Ähnlichkeit natürlich.' },
        { question: 'Wo eignet sich der Studio-Look?', answer: 'Für Führungskräfte, Beratung, Speaker-Seiten, Presseprofile, Premium-Services und Präsentationen.' },
      ],
    },
    ja: {
      title: 'スタジオ風AIヘッドショット',
      description: '撮影予約なしで、きれいな光、シンプルな背景、仕事向けのスタジオ風AI写真を作成します。',
      keywords: ['スタジオ写真 AI', 'AIヘッドショット スタジオ', 'プロフィール写真 スタジオ風', '仕事用写真 AI'],
      eyebrow: 'スタジオ風プロフィール写真',
      h1: '撮影予約なしで作れるスタジオ風AIヘッドショット',
      intro: 'スタジオ風の写真は、通常のプロフィール写真よりも少しきちんと見せたいときに役立ちます。役員紹介、士業、コンサルタント、講師、登壇者、プレミアムサービスの紹介ページでは、光と背景が整っているだけで印象が変わります。このページは、写真館を予約せずに、清潔感のある背景、自然な肌の質感、本人らしい表情、仕事に合う服装をそろえた写真を作りたい人向けです。',
      primaryCta: 'スタジオ風写真を生成',
      secondaryCta: 'サンプルを見る',
      casesTitle: 'スタジオ風が合う場面',
      casesText: '自然さよりも、光や背景の整い方を重視したい場面に向いています。',
      cases: [
        { title: '役員・代表プロフィール', text: '会社紹介、メディア、登壇ページで落ち着いた印象にします。' },
        { title: '専門サービス', text: '士業、コンサル、講師、金融系サービスで信頼感を出します。' },
        { title: 'イベント・広報資料', text: '紹介文や資料に使いやすい、整った写真を用意できます。' },
      ],
      guidanceTitle: '自然に見せるポイント',
      guidanceText: 'スタジオ風でも、加工しすぎに見えないことが大切です。背景はシンプルに、服装は実際の仕事に合うものを選び、顔の質感を残します。',
      checklist: ['やわらかく整った光', 'シンプルな背景', '仕事に合う服装', '自然な肌質と本人らしさ'],
      linksTitle: 'フォーマル度を比較する',
      linksText: '仕事用、企業向け、サンプル、料金を確認できます。',
      relatedLinks: localizedRelated.ja['ai-headshot-studio-style'],
      faqTitle: 'スタジオ風写真の質問',
      faqText: 'きれいに見せながら不自然にしないための確認です。',
      faqs: [
        { question: '企業向け写真と何が違いますか？', answer: 'スタジオ風は光と背景の整い方を重視します。企業向けはチーム全体の統一感を重視します。' },
        { question: '加工しすぎに見えませんか？', answer: '明るい元写真を使い、自然なスタイルを選ぶことで、肌や表情の違和感を抑えられます。' },
        { question: 'どこで使えますか？', answer: '役員紹介、講師プロフィール、メディア資料、専門サービスのページ、提案資料に使いやすいです。' },
      ],
    },
  },
  'ai-headshot-professional-photo': {
    en: {
      title: 'AI Professional Photo Maker for Work Profiles',
      description: 'Create a professional AI photo for LinkedIn, resumes, bios, directories, websites, and business profiles.',
      keywords: ['AI professional photo', 'professional photo maker AI', 'AI business photo', 'professional profile photo AI'],
      eyebrow: 'Professional profile photo use case',
      h1: 'AI Professional Photo Maker for Work Profiles, Bios, and Business Pages',
      intro: 'A professional photo is the flexible version of a headshot: not only for LinkedIn, not only for a resume, and not necessarily as formal as a studio portrait. It needs to work across business bios, directories, email signatures, portfolio pages, conference profiles, and internal systems. This page is for people who want one reliable image set that can travel across those contexts. The best result usually looks current, clear, and easy to recognize, with enough polish to feel intentional and enough naturalness to still feel like you.',
      primaryCta: 'Generate professional photos',
      secondaryCta: 'See examples',
      casesTitle: 'Professional photo use cases',
      casesText: 'Use this page when you need a versatile work image rather than a highly narrow style.',
      cases: [
        { title: 'Business bios and websites', text: 'Create a portrait that works beside service descriptions and contact details.' },
        { title: 'Directories and email signatures', text: 'Use a readable image that still works at small sizes.' },
        { title: 'Portfolio and conference profiles', text: 'Choose a polished but human image for public introductions.' },
      ],
      guidanceTitle: 'Choosing a versatile professional photo',
      guidanceText: 'Aim for an image that can handle multiple contexts. Avoid extreme backgrounds, overly casual clothing, and expressions that only fit one platform.',
      checklist: ['Recognizable face and balanced crop', 'Wardrobe that fits several work contexts', 'Background that feels professional but not distracting', 'Expression that feels confident and human'],
      linksTitle: 'Narrow the photo for each channel',
      linksText: 'Use these pages to tune the same source photos for LinkedIn, resume, or studio-style output.',
      relatedLinks: englishRelated['ai-headshot-professional-photo'],
      faqTitle: 'Professional AI photo questions',
      faqText: 'How to create a flexible image for multiple work contexts.',
      faqs: [
        { question: 'How is this different from a LinkedIn headshot?', answer: 'A LinkedIn headshot is tuned for profile discovery. A professional photo is broader and can work on bios, directories, resumes, websites, and signatures.' },
        { question: 'Can I generate several professional looks?', answer: 'Yes. Use credits to generate selected styles, then keep the versions that fit different contexts.' },
        { question: 'What makes a professional photo look credible?', answer: 'Current likeness, clean lighting, simple styling, and an expression that matches the level of trust your role requires.' },
      ],
    },
    es: {
      title: 'Creador de foto profesional con IA',
      description: 'Crea una foto profesional con IA para LinkedIn, CV, bio, web, directorios y perfiles de negocio.',
      keywords: ['foto profesional IA', 'creador foto profesional IA', 'foto de perfil profesional IA', 'foto negocio IA'],
      eyebrow: 'Foto profesional flexible',
      h1: 'Creador de foto profesional con IA para perfiles, bios y páginas de negocio',
      intro: 'Una foto profesional no siempre tiene que ser tan formal como un retrato de estudio ni tan específica como una foto para LinkedIn. Debe funcionar en bio de empresa, firma de email, directorio interno, portafolio, conferencia, CV o perfil comercial. En mercados hispanohablantes, donde una misma imagen suele circular entre web, WhatsApp profesional, LinkedIn y materiales de ventas, conviene que sea clara, actual y adaptable. Esta página ayuda a crear un set que parezca cuidado sin perder naturalidad.',
      primaryCta: 'Generar fotos profesionales',
      secondaryCta: 'Ver ejemplos',
      casesTitle: 'Usos de una foto profesional',
      casesText: 'Elige este enfoque cuando necesitas una imagen versátil para varios canales.',
      cases: [
        { title: 'Bio y web de negocio', text: 'Acompaña servicios, contacto y página de equipo con una imagen cuidada.' },
        { title: 'Firma y directorio', text: 'Funciona en tamaños pequeños sin perder reconocimiento.' },
        { title: 'Portafolio y eventos', text: 'Da una presentación pública profesional y cercana.' },
      ],
      guidanceTitle: 'Elegir una foto versátil',
      guidanceText: 'Evita fondos extremos, ropa demasiado casual o expresiones que solo funcionen en una red social. Busca una imagen que puedas usar en varias situaciones.',
      checklist: ['Rostro reconocible', 'Ropa útil en varios contextos', 'Fondo profesional sin distracción', 'Expresión segura y humana'],
      linksTitle: 'Ajusta la foto por canal',
      linksText: 'Usa estas páginas para orientar la imagen a LinkedIn, CV o estilo estudio.',
      relatedLinks: localizedRelated.es['ai-headshot-professional-photo'],
      faqTitle: 'Preguntas sobre foto profesional IA',
      faqText: 'Cómo crear una imagen flexible para trabajo y negocio.',
      faqs: [
        { question: '¿En qué se diferencia de una foto para LinkedIn?', answer: 'La de LinkedIn se orienta al perfil público; la foto profesional es más amplia y sirve para bio, web, firma, CV y directorios.' },
        { question: '¿Puedo generar varios looks?', answer: 'Sí. Usa créditos para generar estilos distintos y conserva las versiones que encajan con cada canal.' },
        { question: '¿Qué hace que parezca creíble?', answer: 'Parecido actual, buena luz, ropa sencilla y una expresión acorde al nivel de confianza que requiere tu rol.' },
      ],
    },
    fr: {
      title: 'Créateur de photo professionnelle IA',
      description: 'Créez une photo professionnelle IA pour LinkedIn, CV, bio, site, annuaire et profils business.',
      keywords: ['photo professionnelle IA', 'createur photo professionnelle IA', 'photo profil professionnel IA', 'photo business IA'],
      eyebrow: 'Photo professionnelle polyvalente',
      h1: 'Créateur de photo professionnelle IA pour profils, bios et pages business',
      intro: 'Une photo professionnelle polyvalente n est pas forcément aussi formelle qu un portrait studio ni aussi ciblée qu une photo LinkedIn. Elle doit pouvoir passer d une bio entreprise à une signature e-mail, un annuaire, un portfolio, une page Malt, une conférence ou un CV. Pour les indépendants, consultants, managers et équipes commerciales francophones, l enjeu est d avoir une image claire, actuelle et crédible, assez soignée pour inspirer confiance, mais assez naturelle pour rester reconnaissable.',
      primaryCta: 'Générer des photos professionnelles',
      secondaryCta: 'Voir les exemples',
      casesTitle: 'Usages d une photo professionnelle',
      casesText: 'Choisissez ce format lorsque l image doit rester utile sur plusieurs supports.',
      cases: [
        { title: 'Bio et site business', text: 'Un portrait clair à côté des services, contacts et pages équipe.' },
        { title: 'Signature et annuaire', text: 'Une image lisible même en petit format.' },
        { title: 'Portfolio et événements', text: 'Une présentation publique soignée mais humaine.' },
      ],
      guidanceTitle: 'Choisir une photo polyvalente',
      guidanceText: 'Évitez les fonds trop marqués, les tenues trop casual et les expressions adaptées à une seule plateforme. Cherchez un rendu qui traverse plusieurs contextes.',
      checklist: ['Visage reconnaissable', 'Tenue compatible avec plusieurs usages', 'Fond professionnel discret', 'Expression confiante et naturelle'],
      linksTitle: 'Adapter la photo par canal',
      linksText: 'Ces pages aident à orienter le rendu vers LinkedIn, CV ou studio.',
      relatedLinks: localizedRelated.fr['ai-headshot-professional-photo'],
      faqTitle: 'Questions photo professionnelle IA',
      faqText: 'Créer une image flexible pour plusieurs usages de travail.',
      faqs: [
        { question: 'Quelle différence avec une photo LinkedIn ?', answer: 'LinkedIn vise la découverte de profil. Une photo professionnelle est plus large et peut servir aux bios, sites, signatures, CV et annuaires.' },
        { question: 'Puis-je générer plusieurs looks ?', answer: 'Oui. Générez les styles dont vous avez besoin, puis gardez les versions adaptées à chaque canal.' },
        { question: 'Qu est-ce qui rend la photo crédible ?', answer: 'Une ressemblance actuelle, une lumière propre, une tenue simple et une expression alignée au rôle.' },
      ],
    },
    de: {
      title: 'KI Professional Photo Maker für Berufsprofile',
      description: 'Erstelle ein professionelles KI Foto für LinkedIn, Lebenslauf, Bio, Websites, Verzeichnisse und Business-Profile.',
      keywords: ['professionelles Foto KI', 'Professional Photo Maker KI', 'Business Foto KI', 'Profilfoto KI beruflich'],
      eyebrow: 'Professionelles Profilfoto',
      h1: 'KI Professional Photo Maker für Berufsprofile, Bios und Business-Seiten',
      intro: 'Ein professionelles Foto ist die vielseitige Variante eines Headshots: nicht nur für LinkedIn, nicht nur für den Lebenslauf und nicht zwingend so formell wie ein Studiofoto. In DACH-Kontexten muss ein Bild oft gleichzeitig auf LinkedIn, Xing, Teamseite, E-Mail-Signatur, Speaker-Profil, Portfolio und internem Verzeichnis funktionieren. Diese Seite hilft, ein zuverlässiges Bildset zu erstellen, das aktuell, klar und wiedererkennbar wirkt, mit genug Professionalität für geschäftliche Nutzung und genug Natürlichkeit für echte Wiedererkennung.',
      primaryCta: 'Professionelle Fotos generieren',
      secondaryCta: 'Beispiele ansehen',
      casesTitle: 'Einsatzbereiche',
      casesText: 'Wähle diesen Ansatz, wenn ein Bild auf mehreren beruflichen Kanälen funktionieren soll.',
      cases: [
        { title: 'Bio und Website', text: 'Ein klares Portrait neben Leistungen, Kontakt und Teamprofilen.' },
        { title: 'Signatur und Verzeichnis', text: 'Ein Bild, das auch klein gut lesbar bleibt.' },
        { title: 'Portfolio und Events', text: 'Eine professionelle, aber menschliche öffentliche Vorstellung.' },
      ],
      guidanceTitle: 'Vielseitiges Profilfoto wählen',
      guidanceText: 'Vermeide extreme Hintergründe, zu lockere Kleidung und Ausdrücke, die nur auf einer Plattform funktionieren. Ziel ist ein Bild für mehrere Kontexte.',
      checklist: ['Wiedererkennbares Gesicht', 'Kleidung für mehrere berufliche Situationen', 'Professioneller, ruhiger Hintergrund', 'Souveräner und natürlicher Ausdruck'],
      linksTitle: 'Für einzelne Kanäle zuschneiden',
      linksText: 'Nutze verwandte Seiten für LinkedIn, Lebenslauf und Studio-Look.',
      relatedLinks: localizedRelated.de['ai-headshot-professional-photo'],
      faqTitle: 'Fragen zum professionellen KI Foto',
      faqText: 'So entsteht ein flexibles Bild für mehrere berufliche Kontexte.',
      faqs: [
        { question: 'Was ist anders als bei einem LinkedIn Headshot?', answer: 'LinkedIn ist auf Profilsuche ausgerichtet. Ein professionelles Foto ist breiter und passt auch zu Bios, Websites, Signaturen, Lebenslauf und Verzeichnissen.' },
        { question: 'Kann ich mehrere Looks generieren?', answer: 'Ja. Generiere ausgewählte Stile und behalte die Versionen, die zu den jeweiligen Kanälen passen.' },
        { question: 'Was macht ein professionelles Foto glaubwürdig?', answer: 'Aktuelle Ähnlichkeit, sauberes Licht, einfache Kleidung und ein Ausdruck, der zum Vertrauensniveau deiner Rolle passt.' },
      ],
    },
    ja: {
      title: '仕事用プロフィール写真AIメーカー',
      description: 'LinkedIn、履歴書、自己紹介、会社サイト、社内プロフィールに使える仕事用AI写真を作成します。',
      keywords: ['仕事用 写真 AI', 'プロフィール写真 AI', 'ビジネス写真 AI', 'プロフェッショナル写真 AI'],
      eyebrow: '仕事用プロフィール写真',
      h1: '仕事用プロフィール、自己紹介、ビジネスページに使えるAI写真メーカー',
      intro: '仕事用プロフィール写真は、LinkedInだけ、履歴書だけ、スタジオ写真だけに限定されません。会社サイト、社内プロフィール、メール署名、登壇者紹介、ポートフォリオ、営業資料など、複数の場所で同じ印象を支える写真が必要になることがあります。このページは、ひとつの用途に寄せすぎず、現在の本人らしさ、清潔感、仕事に合う服装、自然な表情を保ちながら、幅広いビジネス場面で使える写真を作りたい人向けです。',
      primaryCta: '仕事用写真を生成',
      secondaryCta: 'サンプルを見る',
      casesTitle: '仕事用写真の使い道',
      casesText: 'ひとつの写真を複数のプロフィールで使いたいときに向いています。',
      cases: [
        { title: '会社サイトと自己紹介', text: 'サービス説明や連絡先の横に置いても自然な写真にします。' },
        { title: '社内プロフィールと署名', text: '小さく表示されても顔がわかりやすい写真にします。' },
        { title: '登壇・ポートフォリオ', text: '公開プロフィールに使える、整った印象を作ります。' },
      ],
      guidanceTitle: '使いやすい写真の選び方',
      guidanceText: '背景が強すぎる写真、カジュアルすぎる服装、特定のSNSだけに合う表情は避けます。複数の仕事場面で違和感がない写真を選びます。',
      checklist: ['本人とわかる顔', '複数の仕事場面に合う服装', '主張しすぎない背景', '信頼感と自然さのある表情'],
      linksTitle: '用途別に調整する',
      linksText: 'LinkedIn、履歴書、スタジオ風、FAQを確認できます。',
      relatedLinks: localizedRelated.ja['ai-headshot-professional-photo'],
      faqTitle: '仕事用AI写真の質問',
      faqText: '複数の仕事場面で使える写真の作り方について。',
      faqs: [
        { question: 'LinkedIn用写真と何が違いますか？', answer: 'LinkedIn用はプロフィール検索向けです。仕事用写真は会社サイト、自己紹介、署名、履歴書などにも使える広い用途を想定しています。' },
        { question: '複数の雰囲気を作れますか？', answer: 'はい。必要なスタイルを生成し、用途に合うものを選べます。' },
        { question: '信頼感のある写真にするには？', answer: '現在の本人らしさ、明るい顔、シンプルな服装、役割に合う表情を優先してください。' },
      ],
    },
  },
}

export function getUseCasePageContent(slug: UseCasePageSlug, locale: Locale) {
  return useCasePages[slug][locale]
}

export function isUseCasePageSlug(value: string): value is UseCasePageSlug {
  return (USE_CASE_PAGE_SLUGS as readonly string[]).includes(value)
}

export function buildUseCasePageMetadata({
  slug,
  locale,
  keywords,
}: {
  slug: UseCasePageSlug
  locale: Locale
  keywords?: string[]
}): Metadata {
  const content = getUseCasePageContent(slug, locale)
  const path = `/${slug}`
  const siteUrl = appConfig.url.replace(/\/$/, '')

  return {
    title: content.title,
    description: content.description,
    keywords: keywords ?? content.keywords,
    alternates: {
      canonical: localePath(locale, path),
      languages: languageAlternatesForPath(path),
    },
    openGraph: {
      title: content.title,
      description: content.description,
      url: localePath(locale, path),
      type: 'website',
      locale: OPEN_GRAPH_LOCALES[locale],
      siteName: appConfig.name,
      images: [
        {
          url: `${siteUrl}${useCaseHeroImage}`,
          width: 1200,
          height: 630,
          alt: content.h1,
        },
      ],
    },
    twitter: {
      card: 'summary_large_image',
      title: content.title,
      description: content.description,
      images: [`${siteUrl}${useCaseHeroImage}`],
    },
  }
}
