-- Migration: 019_enrich_non_professional_style_prompts
-- Description: Enrich non-professional style prompts with stronger visual direction.

BEGIN;

UPDATE headshot_styles AS style
SET
  prompt = updated.prompt,
  negative = updated.negative,
  updated_at = NOW()
FROM (
  VALUES
    ('oil_painting', 'breathtakingly beautiful classical oil painting portrait, rich impasto brush texture, luminous skin tones, deep jewel-toned background, dramatic gallery lighting, ornate fine-art composition, stunning museum masterpiece energy', 'photograph, digital art, smooth plastic skin, 3d render, flat lighting, modern snapshot, clean vector lines, watermark, text, logo'),
    ('watercolor_art', 'ethereal beautiful watercolor portrait, translucent pigment washes, delicate paper grain, blooming color edges, soft luminous background, airy elegant mood, dreamy handcrafted fine-art illustration, gallery-ready finish', 'photograph, harsh ink outlines, 3d render, plastic skin, heavy shadows, pixel-perfect vector art, watermark, text, logo'),
    ('anime_illustration', 'beautiful premium hand-drawn anime portrait, expressive cinematic eyes, soft painted background, gentle magical atmosphere, refined linework, pastel color harmony, warm storybook lighting, stunning animation key-art quality', 'realistic, 3d, photograph, dark, scary, horror, mature, photorealistic'),
    ('cyberpunk_neon', 'stunning cyberpunk neon portrait, rain-slick futuristic street, holographic glow, electric magenta and cyan rim light, sleek techwear, cinematic night atmosphere, sharp high-contrast editorial composition, breathtaking futuristic beauty', 'daylight, rural countryside, vintage historical styling, flat lighting, dull colors, casual office, brand logos, text, watermark'),
    ('pixel_art_retro', 'strikingly beautiful vintage editorial portrait, classic magazine photography, refined retro wardrobe, cinematic film tones, elegant composition, soft studio lighting, premium fashion portrait, collectible cover-image presence', 'pixel art, 16-bit, low resolution, blocky pixels, cartoon, video game style, blurry, distorted face, watermark, text, logo'),
    ('pop_art_comic', 'stunning electric pop art portrait, bold screen-print color blocks, oversized graphic shadows, crisp halftone texture, confident poster composition, playful comic energy, beautiful high-saturation gallery wall impact', 'photograph, realistic skin rendering, muted colors, muddy shadows, dull composition, low contrast, watermark, text, logo'),
    ('coffee_shop', 'beautiful cinematic coffee shop portrait, amber window light, textured wood tables, soft steam atmosphere, relaxed stylish outfit, intimate urban cafe background, dreamy editorial lifestyle mood, shallow depth of field', 'formal, corporate, dark, cold, harsh lighting, studio'),
    ('beach_golden_hour', 'breathtaking luxury beach golden hour portrait, glowing sunset horizon, soft ocean spray, wind-touched linen styling, warm bronze rim light, relaxed natural smile, beautiful travel editorial composition, shallow depth of field', 'studio, formal suit, winter, snow, dark, indoor, harsh lighting, overcast'),
    ('autumn_park', 'beautiful romantic autumn park portrait, golden canopy of leaves, warm copper and amber tones, cozy layered sweater, gentle confident smile, cinematic backlight, crisp fall air atmosphere, stunning editorial lifestyle finish', 'summer, beach, bright sun, harsh lighting, cold winter, studio'),
    ('city_street', 'stunning stylish urban street portrait, layered city lights, modern architecture depth, confident candid pose, polished streetwear-inspired outfit, editorial street photography energy, crisp natural motion and beautiful premium bokeh', 'studio, formal, boring background, dark, blurry'),
    ('library_study', 'beautiful atmospheric library portrait, tall bookshelves, warm brass reading lamps, refined intellectual styling, calm thoughtful expression, cozy textured sweater, cinematic scholar mood, elegant depth and dreamy soft shadows', 'casual, party, bright neon, modern tech, dark, blurry'),
    ('garden_spring', 'ethereal enchanted spring garden portrait, layered blossom branches, pastel floral haze, soft elegant outfit, fresh luminous skin tones, gentle smile, dreamy natural backlight, stunning romantic editorial garden atmosphere', 'winter, dark, cold, formal suit, studio, harsh lighting'),
    ('spring_blossom', 'radiant beautiful spring blossom portrait, pink petals floating in soft air, pastel floral tunnel background, fresh luminous lighting, elegant seasonal styling, joyful renewal mood, stunning romantic portrait finish', 'winter, dark, cold, harsh lighting, autumn, summer heat'),
    ('summer_sunshine', 'vivid stunning summer sunshine portrait, sparkling golden light, lush outdoor color, breezy warm-weather styling, happy confident expression, energetic travel-magazine mood, beautiful crisp highlights and vibrant contrast', 'winter, cold, dark, studio, formal, overcast'),
    ('autumn_foliage', 'cinematic beautiful autumn foliage portrait, fiery red and gold leaves, glowing late-afternoon backlight, cozy refined styling, gentle smile, rich seasonal color grading, stunning warm storybook atmosphere', 'summer, beach, bright sun, winter snow, studio'),
    ('winter_snow', 'magical beautiful winter snow portrait, delicate falling snow, elegant winter coat, rosy cheeks, blue-hour sparkle, warm glowing smile, ethereal fairytale frost atmosphere, stunning cinematic holiday-card finish', 'summer, beach, hot, sweating, bright sun, tropical, shorts, sand'),
    ('black_white_classic', 'timeless beautiful black and white portrait, sculptural contrast, elegant silver-gelatin film texture, dramatic cheekbone shadows, classic studio glamour, stunning fine-art monochrome composition, iconic gallery print presence', 'color, neon, cheap filters, overexposed highlights, flat lighting, muddy gray tones, watermark, text, logo'),
    ('vintage_film', 'beautiful vintage film portrait, tactile grain texture, nostalgic mid-century wardrobe cues, warm faded color palette, soft lens bloom, dreamy cinematic magazine composition, timeless analog photography mood', 'modern digital, high tech, neon, futuristic, clean digital art'),
    ('rembrandt_lighting', 'stunning dramatic chiaroscuro portrait, precise triangular cheek light, deep velvet shadows, painterly classical atmosphere, dignified pose, beautiful museum-quality fine-art lighting, powerful cinematic depth', 'flat lighting, bright even lighting, modern digital, casual, boring'),
    ('soft_glamour', 'stunning soft glamour beauty portrait, luminous diffused key light, polished makeup, silky highlights, elegant pose, refined wardrobe, premium magazine beauty retouching, beautiful luxurious yet natural finish', 'harsh lighting, casual snapshot, messy styling, heavy distortion, plastic skin, blurry, watermark, text, logo'),
    ('superhero_style', 'stunning original superhero movie-poster portrait, dramatic storm-lit sky, dynamic heroic pose, sculpted cape movement, powerful rim lighting, epic cinematic scale, beautiful premium fantasy costume design, no franchise branding', 'known superhero costume, franchise logo, brand emblem, casual clothes, ordinary background, dull lighting, weapon, text, watermark'),
    ('royal_portrait', 'breathtaking regal royal portrait painting, opulent palace backdrop, embroidered ceremonial attire, jewel-toned fabrics, refined crown-like ornament, dignified posture, luminous oil texture, stunning museum masterpiece grandeur', 'modern, casual, everyday, boring, plain background, digital art'),
    ('astronaut_space', 'breathtaking cinematic astronaut portrait, deep starfield and glowing nebula backdrop, sleek generic space suit, reflective helmet details, blue-white rim lighting, stunning sci-fi exploration mood, beautiful cosmic atmosphere, no real-world agency branding, no national symbols', 'NASA logo, NASA text, space agency logo, national flag, flag patch, country flag, official insignia, mission patch, government emblem, earth, normal clothes, casual, boring, plain background, text, watermark'),
    ('comic_book_style', 'stunning premium comic-book cover portrait, bold ink contour lines, explosive color blocking, heroic close-up framing, dramatic speed-line energy, crisp halftone shading, beautiful modern graphic novel polish', 'low quality, blurry, distorted face, extra limbs, extra fingers, watermark, text, cropped image, franchise logo, brand emblem'),
    ('multiverse_adventure', 'breathtaking cinematic multiverse adventure portrait, luminous portal rings, fractured reality layers, dimensional light streaks, futuristic wardrobe, vivid color contrast, stunning sci-fi storytelling, blockbuster key-art finish', 'low quality, blurry, distorted face, extra limbs, extra fingers, watermark, text, cropped image, franchise logo, brand emblem'),
    ('cosplay_hero', 'beautiful high-end original cosplay hero portrait, intricate handmade costume details, dramatic convention spotlight, confident character pose, polished makeup, cinematic fantasy styling, stunning social-media reveal image', 'low quality, blurry, distorted face, extra limbs, extra fingers, watermark, text, cropped image, franchise logo, copied character costume'),
    ('instagram_creator', 'beautiful premium Instagram creator portrait, sunlit lifestyle set, clean but eye-catching composition, trend-aware outfit styling, confident expression, glossy personal-brand finish, stunning scroll-stopping creator profile image', 'low quality, blurry, distorted face, extra limbs, extra fingers, watermark, text, cropped image, brand logo'),
    ('tiktok_trend', 'stunning dynamic short-video creator portrait, playful motion energy, vibrant color accents, expressive pose, fresh street-to-studio styling, crisp face detail, beautiful thumbnail-ready social media impact', 'low quality, blurry, distorted face, extra limbs, extra fingers, watermark, text, cropped image, brand logo'),
    ('editorial_fashion', 'breathtaking editorial fashion portrait, sculptural wardrobe silhouette, runway-inspired attitude, premium magazine lighting, high-fashion color grading, powerful negative space, stunning cover-worthy luxury composition', 'low quality, blurry, distorted face, extra limbs, extra fingers, watermark, text, cropped image, brand logo'),
    ('streetwear_drop', 'stunning streetwear drop portrait, bold urban fashion layers, clean sneaker-focused styling, concrete-and-glass city backdrop, confident relaxed pose, crisp flash-lit editorial edge, beautiful campaign-ready lookbook finish', 'low quality, blurry, distorted face, extra limbs, extra fingers, watermark, text, cropped image, brand logo'),
    ('neon_dreamscape', 'breathtaking surreal neon dreamscape portrait, glowing vapor color fields, glossy cinematic highlights, floating light particles, futuristic makeup accents, electric atmosphere, stunning digital-art poster finish', 'low quality, blurry, distorted face, extra limbs, extra fingers, watermark, text, cropped image, brand logo'),
    ('luxury_boutique', 'beautiful luxury boutique portrait, soft premium retail lighting, elegant tailored wardrobe, marble and warm-metal interior accents, composed refined pose, upscale personal-brand polish, stunning high-end catalog finish', 'low quality, blurry, distorted face, extra limbs, extra fingers, watermark, text, cropped image, brand logo'),
    ('podcast_host', 'beautiful podcast host portrait, warm acoustic studio atmosphere, cinematic desk lighting, premium microphone-side framing, relaxed conversational confidence, tasteful sound-panel texture, stunning creator-brand image with editorial polish', 'low quality, blurry, distorted face, extra limbs, extra fingers, watermark, text, cropped image, visible brand logo'),
    ('gamer_streamer', 'stunning gamer streamer portrait, immersive RGB room glow, layered monitor bokeh, expressive high-energy personality, sleek headset styling, neon accent rim light, beautiful livestream channel-art impact', 'low quality, blurry, distorted face, extra limbs, extra fingers, watermark, text, cropped image, visible brand logo'),
    ('travel_creator', 'breathtaking travel creator portrait, cinematic destination backdrop, sunlit golden atmosphere, stylish practical travel outfit, wanderlust storytelling mood, vibrant local color, beautiful magazine journey cover feel', 'low quality, blurry, distorted face, extra limbs, extra fingers, watermark, text, cropped image, visible brand logo'),
    ('fitness_brand', 'beautiful fitness brand portrait, athletic editorial lighting, clean modern training environment, strong confident posture, crisp activewear styling, energetic wellness-brand mood, stunning sculpted natural highlights', 'low quality, blurry, distorted face, extra limbs, extra fingers, watermark, text, cropped image, visible brand logo'),
    ('beauty_influencer', 'stunning beauty influencer portrait, luminous skin-focused lighting, polished makeup artistry, glossy editorial highlights, refined close-up composition, soft luxury color palette, beautiful premium beauty campaign finish', 'low quality, blurry, distorted face, extra limbs, extra fingers, watermark, text, cropped image, visible brand logo'),
    ('music_artist', 'stunning music artist portrait, moody stage-inspired lighting, expressive performance aura, fashion-forward styling, cinematic shadows, album-cover composition, beautiful creative personal-brand intensity, dramatic color grade', 'low quality, blurry, distorted face, extra limbs, extra fingers, watermark, text, cropped image, visible brand logo'),
    ('fashion_portrait', 'stunning fashion portrait, sculptural editorial wardrobe, runway-inspired attitude, precise luxury lighting, striking pose geometry, premium magazine negative space, beautiful bold cover-worthy composition', 'low quality, blurry, distorted face, extra limbs, extra fingers, watermark, text, cropped image, visible brand logo'),
    ('cinematic_portrait', 'stunning cinematic portrait, dramatic practical lighting, filmic teal-warm color contrast, story-driven expression, atmospheric background depth, beautiful premium still-frame composition, polished high-detail movie poster finish', 'low quality, blurry, distorted face, extra limbs, extra fingers, watermark, text, cropped image, visible brand logo'),
    ('oriental_classic', 'beautiful oriental classic portrait, refined eastern aesthetic, silk-texture styling, warm lantern-like glow, graceful posture, poetic interior depth, timeless cultural elegance, stunning art-book cover finish', 'low quality, blurry, distorted face, extra limbs, extra fingers, watermark, text, cropped image, costume stereotype, visible brand logo'),
    ('hanfu_elegance', 'ethereal hanfu elegance portrait, layered flowing fabric, delicate embroidery details, graceful hand posture, poetic garden or pavilion atmosphere, soft natural backlight, breathtaking Chinese classical beauty, cinematic cultural portrait', 'low quality, blurry, distorted face, extra limbs, extra fingers, watermark, text, cropped image, costume stereotype, visible brand logo'),
    ('ink_wash_art', 'beautiful ink wash portrait, expressive monochrome brush texture, misty mountain negative space, serene face detail, rice-paper grain, restrained elegant composition, ethereal shui-mo fine-art poster mood', 'low quality, blurry, distorted face, extra limbs, extra fingers, watermark, text, cropped image, muddy gray, visible brand logo'),
    ('guofeng_portrait', 'stunning modern guofeng portrait, refined traditional motifs, elegant hair and fabric details, rich lacquer-red and jade accent palette, cinematic soft glow, beautiful cultural fashion editorial finish', 'low quality, blurry, distorted face, extra limbs, extra fingers, watermark, text, cropped image, costume stereotype, visible brand logo'),
    ('imperial_portrait', 'breathtaking imperial portrait, ornate eastern royal styling, embroidered ceremonial layers, dignified centered posture, palace depth, jewel-toned cinematic lighting, stunning historical-drama grandeur, museum-level polish', 'low quality, blurry, distorted face, extra limbs, extra fingers, watermark, text, cropped image, costume stereotype, visible brand logo'),
    ('clean_luxury_social', 'beautiful clean luxury social portrait, refined neutral wardrobe, architectural daylight interior, soft cream and charcoal contrast, elegant personal-brand pose, stunning quiet-luxury mood, premium profile image polish', 'low quality, blurry, distorted face, extra limbs, extra fingers, watermark, text, cropped image, visible brand logo')
) AS updated(id, prompt, negative)
WHERE style.id = updated.id
  AND style.category <> 'professional'
  AND style.category <> 'photo_tools';

COMMIT;
