-- Migration: 020_restore_missing_headshot_styles
-- Description: Restore missing headshot style rows on existing databases without rewriting historical migrations.

BEGIN;

ALTER TABLE headshot_styles
  ADD COLUMN IF NOT EXISTS category_order INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS style_order INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS selection_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_selected_at TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS localized_names JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS localized_category_labels JSONB NOT NULL DEFAULT '{}'::jsonb;

CREATE INDEX IF NOT EXISTS idx_headshot_styles_category_order ON headshot_styles(category_order, style_order);
CREATE INDEX IF NOT EXISTS idx_headshot_styles_selection_count ON headshot_styles(selection_count DESC, last_selected_at DESC);
CREATE INDEX IF NOT EXISTS idx_headshot_styles_localized_names ON headshot_styles USING GIN (localized_names);

INSERT INTO headshot_styles (id, name, category, prompt, negative, sort_order, is_active)
VALUES
('linkedin_professional', 'LinkedIn Professional', 'professional', 'professional corporate headshot, linkedin profile photo, business suit, studio lighting, clean white background, confident friendly smile, canon dslr, 85mm lens', 'casual clothes, outdoor, messy hair, dark shadows, blurry, low quality, distorted face, bad anatomy, multiple people', 10, TRUE),
('corporate_office', 'Corporate Office', 'professional', 'corporate business portrait, modern office background, business attire, professional lighting, confident pose, high-end corporate photography', 'casual, messy, unprofessional, dark, blurry, distorted face', 20, TRUE),
('business_casual', 'Business Casual', 'professional', 'business casual portrait, smart casual attire, relaxed professional look, modern startup vibe, natural lighting, friendly expression', 'formal suit, overly corporate, stiff pose, dark, blurry', 30, TRUE),
('executive_portrait', 'Executive Portrait', 'professional', 'executive headshot, c-level executive, confident powerful pose, luxury office background, dramatic lighting, high-end professional photography', 'casual, young, inexperienced, messy, unprofessional, blurry', 40, TRUE),
('doctor_whitecoat', 'Doctor Whitecoat', 'professional', 'medical professional portrait, white coat, stethoscope, clean clinical background, trustworthy expression, healthcare professional', 'casual clothes, messy, unprofessional, dark, distorted face', 50, TRUE),
('modern_tech', 'Modern Tech', 'professional', 'tech professional portrait, modern tech office, casual tech attire, startup environment, natural lighting, friendly smile', 'formal suit, corporate, outdated, dark, blurry', 60, TRUE),
('creative_agency', 'Creative Agency', 'professional', 'creative professional portrait, modern creative agency, trendy stylish outfit, artistic background, vibrant colors, confident creative look', 'corporate suit, boring, dull, dark, blurry', 70, TRUE),
('oil_painting', 'Oil Painting', 'artistic', 'breathtakingly beautiful classical oil painting portrait, rich impasto brush texture, luminous skin tones, deep jewel-toned background, dramatic gallery lighting, ornate fine-art composition, stunning museum masterpiece energy', 'photograph, digital art, smooth plastic skin, 3d render, flat lighting, modern snapshot, clean vector lines, watermark, text, logo', 480, TRUE),
('watercolor_art', 'Watercolor Art', 'artistic', 'ethereal beautiful watercolor portrait, translucent pigment washes, delicate paper grain, blooming color edges, soft luminous background, airy elegant mood, dreamy handcrafted fine-art illustration, gallery-ready finish', 'photograph, harsh ink outlines, 3d render, plastic skin, heavy shadows, pixel-perfect vector art, watermark, text, logo', 490, TRUE),
('anime_illustration', 'Anime Illustration', 'artistic', 'beautiful premium hand-drawn anime portrait, expressive cinematic eyes, soft painted background, gentle magical atmosphere, refined linework, pastel color harmony, warm storybook lighting, stunning animation key-art quality', 'realistic, 3d, photograph, dark, scary, horror, mature, photorealistic', 500, TRUE),
('cyberpunk_neon', 'Cyberpunk Neon', 'artistic', 'stunning cyberpunk neon portrait, rain-slick futuristic street, holographic glow, electric magenta and cyan rim light, sleek techwear, cinematic night atmosphere, sharp high-contrast editorial composition, breathtaking futuristic beauty', 'daylight, rural countryside, vintage historical styling, flat lighting, dull colors, casual office, brand logos, text, watermark', 530, TRUE),
('pixel_art_retro', 'Pixel Art Retro', 'artistic', 'strikingly beautiful vintage editorial portrait, classic magazine photography, refined retro wardrobe, cinematic film tones, elegant composition, soft studio lighting, premium fashion portrait, collectible cover-image presence', 'pixel art, 16-bit, low resolution, blocky pixels, cartoon, video game style, blurry, distorted face, watermark, text, logo', 510, TRUE),
('pop_art_comic', 'Pop Art Comic', 'artistic', 'stunning electric pop art portrait, bold screen-print color blocks, oversized graphic shadows, crisp halftone texture, confident poster composition, playful comic energy, beautiful high-saturation gallery wall impact', 'photograph, realistic skin rendering, muted colors, muddy shadows, dull composition, low contrast, watermark, text, logo', 520, TRUE),
('coffee_shop', 'Coffee Shop', 'lifestyle', 'beautiful cinematic coffee shop portrait, amber window light, textured wood tables, soft steam atmosphere, relaxed stylish outfit, intimate urban cafe background, dreamy editorial lifestyle mood, shallow depth of field', 'formal, corporate, dark, cold, harsh lighting, studio', 370, TRUE),
('beach_golden_hour', 'Beach Golden Hour', 'lifestyle', 'breathtaking luxury beach golden hour portrait, glowing sunset horizon, soft ocean spray, wind-touched linen styling, warm bronze rim light, relaxed natural smile, beautiful travel editorial composition, shallow depth of field', 'studio, formal suit, winter, snow, dark, indoor, harsh lighting, overcast', 350, TRUE),
('autumn_park', 'Autumn Park', 'lifestyle', 'beautiful romantic autumn park portrait, golden canopy of leaves, warm copper and amber tones, cozy layered sweater, gentle confident smile, cinematic backlight, crisp fall air atmosphere, stunning editorial lifestyle finish', 'summer, beach, bright sun, harsh lighting, cold winter, studio', 380, TRUE),
('city_street', 'City Street', 'lifestyle', 'stunning stylish urban street portrait, layered city lights, modern architecture depth, confident candid pose, polished streetwear-inspired outfit, editorial street photography energy, crisp natural motion and beautiful premium bokeh', 'studio, formal, boring background, dark, blurry', 360, TRUE),
('library_study', 'Library Study', 'lifestyle', 'beautiful atmospheric library portrait, tall bookshelves, warm brass reading lamps, refined intellectual styling, calm thoughtful expression, cozy textured sweater, cinematic scholar mood, elegant depth and dreamy soft shadows', 'casual, party, bright neon, modern tech, dark, blurry', 390, TRUE),
('garden_spring', 'Garden Spring', 'lifestyle', 'ethereal enchanted spring garden portrait, layered blossom branches, pastel floral haze, soft elegant outfit, fresh luminous skin tones, gentle smile, dreamy natural backlight, stunning romantic editorial garden atmosphere', 'winter, dark, cold, formal suit, studio, harsh lighting', 400, TRUE),
('spring_blossom', 'Spring Blossom', 'seasonal', 'radiant beautiful spring blossom portrait, pink petals floating in soft air, pastel floral tunnel background, fresh luminous lighting, elegant seasonal styling, joyful renewal mood, stunning romantic portrait finish', 'winter, dark, cold, harsh lighting, autumn, summer heat', 410, TRUE),
('summer_sunshine', 'Summer Sunshine', 'seasonal', 'vivid stunning summer sunshine portrait, sparkling golden light, lush outdoor color, breezy warm-weather styling, happy confident expression, energetic travel-magazine mood, beautiful crisp highlights and vibrant contrast', 'winter, cold, dark, studio, formal, overcast', 340, TRUE),
('autumn_foliage', 'Autumn Foliage', 'seasonal', 'cinematic beautiful autumn foliage portrait, fiery red and gold leaves, glowing late-afternoon backlight, cozy refined styling, gentle smile, rich seasonal color grading, stunning warm storybook atmosphere', 'summer, beach, bright sun, winter snow, studio', 420, TRUE),
('winter_snow', 'Winter Snow', 'seasonal', 'magical beautiful winter snow portrait, delicate falling snow, elegant winter coat, rosy cheeks, blue-hour sparkle, warm glowing smile, ethereal fairytale frost atmosphere, stunning cinematic holiday-card finish', 'summer, beach, hot, sweating, bright sun, tropical, shorts, sand', 430, TRUE),
('black_white_classic', 'Black & White Classic', 'artistic', 'timeless beautiful black and white portrait, sculptural contrast, elegant silver-gelatin film texture, dramatic cheekbone shadows, classic studio glamour, stunning fine-art monochrome composition, iconic gallery print presence', 'color, neon, cheap filters, overexposed highlights, flat lighting, muddy gray tones, watermark, text, logo', 440, TRUE),
('vintage_film', 'Vintage Film', 'artistic', 'beautiful vintage film portrait, tactile grain texture, nostalgic mid-century wardrobe cues, warm faded color palette, soft lens bloom, dreamy cinematic magazine composition, timeless analog photography mood', 'modern digital, high tech, neon, futuristic, clean digital art', 450, TRUE),
('rembrandt_lighting', 'Rembrandt Lighting', 'artistic', 'stunning dramatic chiaroscuro portrait, precise triangular cheek light, deep velvet shadows, painterly classical atmosphere, dignified pose, beautiful museum-quality fine-art lighting, powerful cinematic depth', 'flat lighting, bright even lighting, modern digital, casual, boring', 460, TRUE),
('soft_glamour', 'Soft Glamour', 'artistic', 'stunning soft glamour beauty portrait, luminous diffused key light, polished makeup, silky highlights, elegant pose, refined wardrobe, premium magazine beauty retouching, beautiful luxurious yet natural finish', 'harsh lighting, casual snapshot, messy styling, heavy distortion, plastic skin, blurry, watermark, text, logo', 470, TRUE),
('superhero_style', 'Superhero', 'artistic', 'stunning original superhero movie-poster portrait, dramatic storm-lit sky, dynamic heroic pose, sculpted cape movement, powerful rim lighting, epic cinematic scale, beautiful premium fantasy costume design, no franchise branding', 'known superhero costume, franchise logo, brand emblem, casual clothes, ordinary background, dull lighting, weapon, text, watermark', 560, TRUE),
('royal_portrait', 'Royal Portrait', 'artistic', 'breathtaking regal royal portrait painting, opulent palace backdrop, embroidered ceremonial attire, jewel-toned fabrics, refined crown-like ornament, dignified posture, luminous oil texture, stunning museum masterpiece grandeur', 'modern, casual, everyday, boring, plain background, digital art', 550, TRUE),
('astronaut_space', 'Astronaut Space', 'artistic', 'breathtaking cinematic astronaut portrait, deep starfield and glowing nebula backdrop, sleek generic space suit, reflective helmet details, blue-white rim lighting, stunning sci-fi exploration mood, beautiful cosmic atmosphere, no real-world agency branding, no national symbols', 'NASA logo, NASA text, space agency logo, national flag, flag patch, country flag, official insignia, mission patch, government emblem, earth, normal clothes, casual, boring, plain background, text, watermark', 540, TRUE),
('comic_book_style', 'Comic Book Style', 'artistic', 'stunning premium comic-book cover portrait, bold ink contour lines, explosive color blocking, heroic close-up framing, dramatic speed-line energy, crisp halftone shading, beautiful modern graphic novel polish', 'low quality, blurry, distorted face, extra limbs, extra fingers, watermark, text, cropped image, franchise logo, brand emblem', 150, TRUE),
('multiverse_adventure', 'Multiverse Adventure', 'artistic', 'breathtaking cinematic multiverse adventure portrait, luminous portal rings, fractured reality layers, dimensional light streaks, futuristic wardrobe, vivid color contrast, stunning sci-fi storytelling, blockbuster key-art finish', 'low quality, blurry, distorted face, extra limbs, extra fingers, watermark, text, cropped image, franchise logo, brand emblem', 160, TRUE),
('cosplay_hero', 'Cosplay Hero', 'artistic', 'beautiful high-end original cosplay hero portrait, intricate handmade costume details, dramatic convention spotlight, confident character pose, polished makeup, cinematic fantasy styling, stunning social-media reveal image', 'low quality, blurry, distorted face, extra limbs, extra fingers, watermark, text, cropped image, franchise logo, copied character costume', 140, TRUE),
('instagram_creator', 'Instagram Creator', 'lifestyle', 'beautiful premium Instagram creator portrait, sunlit lifestyle set, clean but eye-catching composition, trend-aware outfit styling, confident expression, glossy personal-brand finish, stunning scroll-stopping creator profile image', 'low quality, blurry, distorted face, extra limbs, extra fingers, watermark, text, cropped image, brand logo', 100, TRUE),
('tiktok_trend', 'TikTok Trend', 'lifestyle', 'stunning dynamic short-video creator portrait, playful motion energy, vibrant color accents, expressive pose, fresh street-to-studio styling, crisp face detail, beautiful thumbnail-ready social media impact', 'low quality, blurry, distorted face, extra limbs, extra fingers, watermark, text, cropped image, brand logo', 110, TRUE),
('editorial_fashion', 'Editorial Fashion', 'artistic', 'breathtaking editorial fashion portrait, sculptural wardrobe silhouette, runway-inspired attitude, premium magazine lighting, high-fashion color grading, powerful negative space, stunning cover-worthy luxury composition', 'low quality, blurry, distorted face, extra limbs, extra fingers, watermark, text, cropped image, brand logo', 130, TRUE),
('streetwear_drop', 'Streetwear Drop', 'lifestyle', 'stunning streetwear drop portrait, bold urban fashion layers, clean sneaker-focused styling, concrete-and-glass city backdrop, confident relaxed pose, crisp flash-lit editorial edge, beautiful campaign-ready lookbook finish', 'low quality, blurry, distorted face, extra limbs, extra fingers, watermark, text, cropped image, brand logo', 120, TRUE),
('neon_dreamscape', 'Neon Dreamscape', 'artistic', 'breathtaking surreal neon dreamscape portrait, glowing vapor color fields, glossy cinematic highlights, floating light particles, futuristic makeup accents, electric atmosphere, stunning digital-art poster finish', 'low quality, blurry, distorted face, extra limbs, extra fingers, watermark, text, cropped image, brand logo', 170, TRUE),
('luxury_boutique', 'Luxury Boutique', 'lifestyle', 'beautiful luxury boutique portrait, soft premium retail lighting, elegant tailored wardrobe, marble and warm-metal interior accents, composed refined pose, upscale personal-brand polish, stunning high-end catalog finish', 'low quality, blurry, distorted face, extra limbs, extra fingers, watermark, text, cropped image, brand logo', 230, TRUE),
('minimal_studio', 'Minimal Studio', 'professional', 'minimal studio portrait, clean background, soft directional lighting, understated wardrobe, modern personal brand aesthetic, crisp composition, high detail', 'low quality, blurry, distorted face, extra limbs, extra fingers, watermark, text, cropped image', 240, TRUE),
('startup_founder', 'Startup Founder', 'professional', 'startup founder portrait, modern office vibe, relaxed confidence, smart casual wardrobe, clean branding, contemporary headshot, high detail', 'low quality, blurry, distorted face, extra limbs, extra fingers, watermark, text, cropped image', 250, TRUE),
('podcast_host', 'Podcast Host', 'lifestyle', 'beautiful podcast host portrait, warm acoustic studio atmosphere, cinematic desk lighting, premium microphone-side framing, relaxed conversational confidence, tasteful sound-panel texture, stunning creator-brand image with editorial polish', 'low quality, blurry, distorted face, extra limbs, extra fingers, watermark, text, cropped image, visible brand logo', 260, TRUE),
('gamer_streamer', 'Gamer Streamer', 'lifestyle', 'stunning gamer streamer portrait, immersive RGB room glow, layered monitor bokeh, expressive high-energy personality, sleek headset styling, neon accent rim light, beautiful livestream channel-art impact', 'low quality, blurry, distorted face, extra limbs, extra fingers, watermark, text, cropped image, visible brand logo', 270, TRUE),
('travel_creator', 'Travel Creator', 'lifestyle', 'breathtaking travel creator portrait, cinematic destination backdrop, sunlit golden atmosphere, stylish practical travel outfit, wanderlust storytelling mood, vibrant local color, beautiful magazine journey cover feel', 'low quality, blurry, distorted face, extra limbs, extra fingers, watermark, text, cropped image, visible brand logo', 280, TRUE),
('fitness_brand', 'Fitness Brand', 'lifestyle', 'beautiful fitness brand portrait, athletic editorial lighting, clean modern training environment, strong confident posture, crisp activewear styling, energetic wellness-brand mood, stunning sculpted natural highlights', 'low quality, blurry, distorted face, extra limbs, extra fingers, watermark, text, cropped image, visible brand logo', 290, TRUE),
('beauty_influencer', 'Beauty Influencer', 'artistic', 'stunning beauty influencer portrait, luminous skin-focused lighting, polished makeup artistry, glossy editorial highlights, refined close-up composition, soft luxury color palette, beautiful premium beauty campaign finish', 'low quality, blurry, distorted face, extra limbs, extra fingers, watermark, text, cropped image, visible brand logo', 300, TRUE),
('music_artist', 'Music Artist', 'artistic', 'stunning music artist portrait, moody stage-inspired lighting, expressive performance aura, fashion-forward styling, cinematic shadows, album-cover composition, beautiful creative personal-brand intensity, dramatic color grade', 'low quality, blurry, distorted face, extra limbs, extra fingers, watermark, text, cropped image, visible brand logo', 310, TRUE),
('fashion_portrait', 'Fashion Portrait', 'artistic', 'stunning fashion portrait, sculptural editorial wardrobe, runway-inspired attitude, precise luxury lighting, striking pose geometry, premium magazine negative space, beautiful bold cover-worthy composition', 'low quality, blurry, distorted face, extra limbs, extra fingers, watermark, text, cropped image, visible brand logo', 320, TRUE),
('creator_headshot', 'Creator Headshot', 'professional', 'creator headshot, modern personal brand portrait, clean composition, approachable confidence, polished social media profile look, high detail', 'low quality, blurry, distorted face, extra limbs, extra fingers, watermark, text, cropped image', 90, TRUE),
('cinematic_portrait', 'Cinematic Portrait', 'artistic', 'stunning cinematic portrait, dramatic practical lighting, filmic teal-warm color contrast, story-driven expression, atmospheric background depth, beautiful premium still-frame composition, polished high-detail movie poster finish', 'low quality, blurry, distorted face, extra limbs, extra fingers, watermark, text, cropped image, visible brand logo', 330, TRUE),
('oriental_classic', 'Oriental Classic', 'artistic', 'beautiful oriental classic portrait, refined eastern aesthetic, silk-texture styling, warm lantern-like glow, graceful posture, poetic interior depth, timeless cultural elegance, stunning art-book cover finish', 'low quality, blurry, distorted face, extra limbs, extra fingers, watermark, text, cropped image, costume stereotype, visible brand logo', 180, TRUE),
('hanfu_elegance', 'Hanfu Elegance', 'artistic', 'ethereal hanfu elegance portrait, layered flowing fabric, delicate embroidery details, graceful hand posture, poetic garden or pavilion atmosphere, soft natural backlight, breathtaking Chinese classical beauty, cinematic cultural portrait', 'low quality, blurry, distorted face, extra limbs, extra fingers, watermark, text, cropped image, costume stereotype, visible brand logo', 190, TRUE),
('ink_wash_art', 'Ink Wash Art', 'artistic', 'beautiful ink wash portrait, expressive monochrome brush texture, misty mountain negative space, serene face detail, rice-paper grain, restrained elegant composition, ethereal shui-mo fine-art poster mood', 'low quality, blurry, distorted face, extra limbs, extra fingers, watermark, text, cropped image, muddy gray, visible brand logo', 210, TRUE),
('guofeng_portrait', 'Guofeng Portrait', 'artistic', 'stunning modern guofeng portrait, refined traditional motifs, elegant hair and fabric details, rich lacquer-red and jade accent palette, cinematic soft glow, beautiful cultural fashion editorial finish', 'low quality, blurry, distorted face, extra limbs, extra fingers, watermark, text, cropped image, costume stereotype, visible brand logo', 200, TRUE),
('imperial_portrait', 'Imperial Portrait', 'artistic', 'breathtaking imperial portrait, ornate eastern royal styling, embroidered ceremonial layers, dignified centered posture, palace depth, jewel-toned cinematic lighting, stunning historical-drama grandeur, museum-level polish', 'low quality, blurry, distorted face, extra limbs, extra fingers, watermark, text, cropped image, costume stereotype, visible brand logo', 220, TRUE),
('clean_luxury_social', 'Clean Luxury Social', 'lifestyle', 'beautiful clean luxury social portrait, refined neutral wardrobe, architectural daylight interior, soft cream and charcoal contrast, elegant personal-brand pose, stunning quiet-luxury mood, premium profile image polish', 'low quality, blurry, distorted face, extra limbs, extra fingers, watermark, text, cropped image, visible brand logo', 80, TRUE)
ON CONFLICT (id) DO NOTHING;

UPDATE headshot_styles
SET
  category_order = CASE category
    WHEN 'professional' THEN 1
    WHEN 'lifestyle' THEN 2
    WHEN 'artistic' THEN 3
    WHEN 'seasonal' THEN 4
    WHEN 'photo_tools' THEN 5
    ELSE 9
  END,
  style_order = sort_order,
  localized_category_labels = COALESCE(localized_category_labels, '{}'::jsonb) ||
    CASE category
      WHEN 'professional' THEN jsonb_build_object('es', 'Profesional', 'fr', 'Professionnel', 'de', 'Professionell', 'ja', 'Professional')
      WHEN 'artistic' THEN jsonb_build_object('es', 'Creativo', 'fr', 'Creatif', 'de', 'Kreativ', 'ja', 'Creative')
      WHEN 'lifestyle' THEN jsonb_build_object('es', 'Lifestyle', 'fr', 'Style de vie', 'de', 'Lifestyle', 'ja', 'Lifestyle')
      WHEN 'seasonal' THEN jsonb_build_object('es', 'Temporada', 'fr', 'Saisonnier', 'de', 'Saisonal', 'ja', 'Seasonal')
      WHEN 'photo_tools' THEN jsonb_build_object('es', 'Foto para imprimir', 'fr', 'Photo a imprimer', 'de', 'Druckfoto', 'ja', 'Print Photo')
      ELSE '{}'::jsonb
    END,
  updated_at = NOW()
WHERE id IN (
  'linkedin_professional', 'corporate_office', 'business_casual', 'executive_portrait',
  'doctor_whitecoat', 'modern_tech', 'creative_agency', 'clean_luxury_social',
  'creator_headshot', 'instagram_creator', 'tiktok_trend', 'streetwear_drop',
  'editorial_fashion', 'cosplay_hero', 'comic_book_style', 'multiverse_adventure',
  'neon_dreamscape', 'oriental_classic', 'hanfu_elegance', 'guofeng_portrait',
  'ink_wash_art', 'imperial_portrait', 'luxury_boutique', 'minimal_studio',
  'startup_founder', 'podcast_host', 'gamer_streamer', 'travel_creator',
  'fitness_brand', 'beauty_influencer', 'music_artist', 'fashion_portrait',
  'cinematic_portrait', 'summer_sunshine', 'beach_golden_hour', 'city_street',
  'coffee_shop', 'autumn_park', 'library_study', 'garden_spring',
  'spring_blossom', 'autumn_foliage', 'winter_snow', 'black_white_classic',
  'vintage_film', 'rembrandt_lighting', 'soft_glamour', 'oil_painting',
  'watercolor_art', 'anime_illustration', 'pixel_art_retro', 'pop_art_comic',
  'cyberpunk_neon', 'astronaut_space', 'royal_portrait', 'superhero_style'
);

COMMIT;
